module

public import UniversalGroup.Simulator.Recognition.FiniteRank.Coefficients
public import UniversalGroup.Simulator.DModel

@[expose] public section

/-! Reduced T words and coefficient transport for arbitrary finite input codes. -/
namespace UniversalGroup.HigmanSimulatorB
noncomputable section
open HNNLemmas
set_option maxHeartbeats 800000
variable {k : ℕ} (D : Data k)

abbrev fromF := SimulatorModel.fromF D.words D.F_support D.E_support
abbrev attaching := SimulatorModel.qSubgroup D.words D.F_support D.E_support
abbrev marker := SimulatorDModel.marker D.words D.F_support D.E_support
abbrev left := TwistedCentralizer.left (attaching D) (marker D)
abbrev right := TwistedCentralizer.right (attaching D) (marker D) (f D)
abbrev phi := UniversalGroup.rangeEquiv (left D) (right D)
  (TwistedCentralizer.left_injective _ _) (TwistedCentralizer.right_injective _ _ _)
abbrev Rebased := SimulatorDModel.Rebased D.words D.F_support D.E_support
abbrev toLiteral := SimulatorDModel.toLiteral D.words D.F_support D.E_support
abbrev ReducedWord := HNNExtension.NormalWord.ReducedWord (FStage D)
  (left D).range (right D).range

private theorem preserves_of_disjoint (H : Subgroup (FStage D))
    (hl : ∀ v : Core D, v ∈ CE D →
      ofCore D (pCore D * v * (pCore D)⁻¹) ∈ H → v = 1)
    (hr : ∀ v : Core D, v ∈ CE D →
      (f D)⁻¹ * ofCore D (pCore D * v * (pCore D)⁻¹) * f D ∈ H → v = 1)
    (a : (left D).range) :
    (a : FStage D) ∈ H ↔ ((phi D a : (right D).range) : FStage D) ∈ H := by
  rcases a with ⟨_, c, rfl⟩
  rw [UniversalGroup.rangeEquiv_apply_range]
  rcases c with ⟨_, v, hv, rfl⟩
  change marker D * ofCore D v * (marker D)⁻¹ ∈ H ↔
    (f D)⁻¹ * (marker D * ofCore D v * (marker D)⁻¹) * f D ∈ H
  have hm : marker D * ofCore D v * (marker D)⁻¹ =
      ofCore D (pCore D * v * (pCore D)⁻¹) := by simp [marker, SimulatorDModel.marker]
  rw [hm]
  constructor
  · intro h
    have hvone := hl v hv h
    simp [hvone]
  · intro h
    have hvone := hr v hv h
    simp [hvone]

theorem preserves_B (a : (left D).range) :
    (a : FStage D) ∈ Base D ↔
      ((phi D a : (right D).range) : FStage D) ∈ Base D :=
  preserves_of_disjoint D _ (attaching_left_disjoint D)
    (attaching_right_disjoint D) a

/-- A literal coefficient group with the new stable letter T adjoined. -/
def factor (H : Subgroup (FStage D)) : Subgroup (simulatorL D.words).Group :=
  generatedWith (H.map (fromF D)) (SimulatorRecognitionForward.target D.words)

/-- The coefficient subgroup with the stable letter in the T presentation. -/
def rebasedFactor (H : Subgroup (FStage D)) : Subgroup (Rebased D) :=
  TwistedCentralizer.rebasedSubgroup (attaching D) (marker D) (f D) H

private theorem ambientFactor_map (H : Subgroup (FStage D)) :
    (TwistedCentralizer.subgroup (attaching D) (marker D) (f D) H).map
      (SimulatorModel.fromModel D.words D.F_support D.E_support) = factor D H := by
  unfold TwistedCentralizer.subgroup factor generatedWith
  rw [Subgroup.closure_union, Subgroup.closure_union, Subgroup.closure_eq,
    Subgroup.closure_eq, Subgroup.map_sup, Subgroup.map_map,
    MonoidHom.map_closure, Set.image_singleton, SimulatorDModel.fromModel_target]
  have hc : (SimulatorModel.fromModel D.words D.F_support D.E_support).comp
      (centralizerOf (attaching D)) = fromF D := by
    apply MonoidHom.ext
    intro x
    exact SimulatorModel.fromModel_ofQ D.words D.F_support D.E_support x
  rw [hc]

/-- Transport of the restricted T subgroup to the literal simulator. -/
theorem rebasedFactor_map (H : Subgroup (FStage D)) :
    (rebasedFactor D H).map (toLiteral D) = factor D H := by
  change (TwistedCentralizer.rebasedSubgroup (attaching D) (marker D) (f D) H).map
    ((SimulatorModel.fromModel D.words D.F_support D.E_support).comp
      (TwistedCentralizer.toAmbient (attaching D) (marker D) (f D))) = _
  rw [← Subgroup.map_map, TwistedCentralizer.map_rebasedSubgroup, ambientFactor_map]

theorem exists_reducedWord_factor (H : Subgroup (FStage D))
    (hp : ∀ a : (left D).range, (a : FStage D) ∈ H ↔
      ((phi D a : (right D).range) : FStage D) ∈ H)
    {x : (simulatorL D.words).Group} (hx : x ∈ factor D H) :
    ∃ w : ReducedWord D, toLiteral D (w.prod (phi D)) = x ∧
      w.head ∈ H ∧ ∀ p ∈ w.toList, p.2 ∈ H := by
  rw [← rebasedFactor_map D H] at hx
  rcases hx with ⟨y,hy,rfl⟩
  obtain ⟨w,hw,hh,ht⟩ := exists_reducedWord_of_mem_generatedWithStable H hp hy
  exact ⟨w,congrArg (toLiteral D) hw,hh,ht⟩

/-- The subgroup generated by the arbitrary input codes, f, and T. -/
abbrev B := factor D (Base D)

theorem exists_reducedWord_B {x : (simulatorL D.words).Group} (hx : x ∈ B D) :
    ∃ w : ReducedWord D, toLiteral D (w.prod (phi D)) = x ∧
      w.head ∈ Base D ∧ ∀ p ∈ w.toList, p.2 ∈ Base D :=
  exists_reducedWord_factor D _ (preserves_B D) hx

abbrev coefficients := SimulatorDModel.coefficients D.words D.F_support D.E_support

theorem left_coefficient_factorization (b a : FStage D)
    (ha : a ∈ coefficients D) (h : b⁻¹ * a ∈ (left D).range) :
    ∃ u v : Core D, u ∈ CD D ∧ v ∈ CE D ∧
      b = ofCore D (u * pCore D * v * (pCore D)⁻¹) := by
  rcases ha with ⟨u, hu, rfl⟩
  rcases h with ⟨c, hc⟩
  rcases c.property with ⟨v, hv, hvc⟩
  have hc' : ofCore D (pCore D * v * (pCore D)⁻¹) =
      b⁻¹ * ofCore D u := by
    simpa only [left, TwistedCentralizer.left_apply, marker, SimulatorDModel.marker,
      ← hvc, map_mul, map_inv] using hc
  have hb : b * ofCore D (pCore D * v * (pCore D)⁻¹) = ofCore D u := by
    rw [hc']
    simp
  refine ⟨u, v⁻¹, hu, (CE D).inv_mem hv, ?_⟩
  calc
    b = (b * ofCore D (pCore D * v * (pCore D)⁻¹)) *
        (ofCore D (pCore D * v * (pCore D)⁻¹))⁻¹ := by group
    _ = ofCore D u * (ofCore D (pCore D * v * (pCore D)⁻¹))⁻¹ := by rw [hb]
    _ = ofCore D (u * pCore D * v⁻¹ * (pCore D)⁻¹) := by
      simp [map_mul, map_inv, mul_assoc]

theorem right_coefficient_factorization (b a : FStage D)
    (ha : a ∈ coefficients D) (h : b⁻¹ * a ∈ (right D).range) :
    ∃ u v : Core D, u ∈ CD D ∧ v ∈ CE D ∧
      b = (f D)⁻¹ * ofCore D (u * pCore D * v * (pCore D)⁻¹) * f D := by
  rcases ha with ⟨u, hu, rfl⟩
  rcases h with ⟨c, hc⟩
  rcases c.property with ⟨v, hv, hvc⟩
  have hc' : (f D)⁻¹ * ofCore D (pCore D * v * (pCore D)⁻¹) * f D =
      b⁻¹ * ofCore D u := by
    simpa only [right, TwistedCentralizer.right_apply, marker, SimulatorDModel.marker,
      ← hvc, map_mul, map_inv] using hc
  have hb : b * ((f D)⁻¹ * ofCore D (pCore D * v * (pCore D)⁻¹) * f D) =
      ofCore D u := by
    rw [hc']
    simp
  have hcomm : Commute (f D) (ofCore D u) :=
    SimulatorDModel.f_commutes D.words D.F_support D.E_support _ ⟨u, hu, rfl⟩
  refine ⟨u, v⁻¹, hu, (CE D).inv_mem hv, ?_⟩
  calc
    b = (b * ((f D)⁻¹ * ofCore D (pCore D * v * (pCore D)⁻¹) * f D)) *
        ((f D)⁻¹ * ofCore D (pCore D * v * (pCore D)⁻¹) * f D)⁻¹ := by group
    _ = ofCore D u *
        ((f D)⁻¹ * ofCore D (pCore D * v * (pCore D)⁻¹) * f D)⁻¹ := by rw [hb]
    _ = (f D)⁻¹ * ofCore D (u * pCore D * v⁻¹ * (pCore D)⁻¹) * f D := by
      simp only [map_mul, map_inv, mul_inv_rev, inv_inv, mul_assoc]
      rw [← mul_assoc, hcomm.symm.inv_right.eq, mul_assoc]

end
end UniversalGroup.HigmanSimulatorB
