module

public import UniversalGroup.Foundations.HNN.NormalForms
public import UniversalGroup.Foundations.Presentation

@[expose] public section

/-! Adjoining a centralizer stable letter to a disjoint free subgroup. -/

namespace UniversalGroup.AdjoinFree

open HNNLemmas

noncomputable section

variable {G : Type*} [Group G] {n : ℕ}
  (C : Subgroup G) (σ : FreeGroup (Fin n) →* G)

/-- Retain the original free generators and append the stable letter. -/
def hom : FreeGroup (Fin (n + 1)) →* CentralizerHNN G C :=
  FreeGroup.lift (Fin.lastCases (centralizerStable C)
    (fun i => centralizerOf C (σ (FreeGroup.of i))))

@[simp] theorem hom_old (i : Fin n) :
    hom C σ (FreeGroup.of i.castSucc) = centralizerOf C (σ (FreeGroup.of i)) := by
  simp [hom]

@[simp] theorem hom_last :
    hom C σ (FreeGroup.of (Fin.last n)) = centralizerStable C := by
  simp [hom]

theorem hom_comp_old : (hom C σ).comp (FreeGroup.map Fin.castSucc) =
    (centralizerOf C).comp σ := by
  apply FreeGroup.ext_hom
  intro i
  simp

private abbrev Restricted :=
  HNNExtension σ.range (restrictedA (A := C) σ.range) (restrictedB (B := C) σ.range)
    (restrictedPhi (phi := MulEquiv.refl C) σ.range (fun _ => Iff.rfl))

private def baseGenerator (i : Fin n) : σ.range :=
  ⟨σ (FreeGroup.of i), ⟨FreeGroup.of i, rfl⟩⟩

private def freeToRestricted : FreeGroup (Fin (n + 1)) →* Restricted C σ :=
  FreeGroup.lift (Fin.lastCases HNNExtension.t
    (fun i => HNNExtension.of (baseGenerator σ i)))

variable (hσ : Function.Injective σ) (hdisj : σ.range ⊓ C = ⊥)

private def baseToFree : σ.range →* FreeGroup (Fin (n + 1)) :=
  (FreeGroup.map Fin.castSucc).comp (MonoidHom.ofInjective hσ).symm.toMonoidHom

private theorem baseToFree_generator (i : Fin n) :
    baseToFree σ hσ (baseGenerator σ i) = FreeGroup.of i.castSucc := by
  have h : (MonoidHom.ofInjective hσ) (FreeGroup.of i) = baseGenerator σ i := rfl
  rw [← h]
  simp [baseToFree]

private def restrictedToFree : Restricted C σ →* FreeGroup (Fin (n + 1)) :=
  HNNExtension.lift (baseToFree σ hσ) (FreeGroup.of (Fin.last n)) (by
    intro a
    have ha : a = 1 := by
      apply Subtype.ext
      apply Subtype.ext
      have h : (((a : σ.range) : G)) ∈ (⊥ : Subgroup G) := by
        rw [← hdisj]
        exact ⟨(a : σ.range).property, a.property⟩
      exact h
    subst a
    simp)

include hσ hdisj in
private theorem freeToRestricted_injective : Function.Injective (freeToRestricted C σ) := by
  have h : (restrictedToFree C σ hσ hdisj).comp (freeToRestricted C σ) = MonoidHom.id _ := by
    apply FreeGroup.ext_hom
    intro i
    refine Fin.lastCases ?_ (fun j => ?_) i
    · simp [freeToRestricted, restrictedToFree]
    · simp [freeToRestricted, restrictedToFree, baseToFree_generator]
  exact Function.LeftInverse.injective (fun x => DFunLike.congr_fun h x)

include hσ hdisj in
theorem hom_injective : Function.Injective (hom C σ) := by
  have h : (restrictedEmbedding (phi := MulEquiv.refl C) σ.range (fun _ => Iff.rfl)).comp
      (freeToRestricted C σ) = hom C σ := by
    apply FreeGroup.ext_hom
    intro i
    refine Fin.lastCases ?_ (fun j => ?_) i
    · simp [freeToRestricted, hom, centralizerStable]
      exact restrictedEmbedding_t σ.range (fun _ => Iff.rfl)
    · simp [freeToRestricted, hom, baseGenerator, centralizerOf]
      exact restrictedEmbedding_of σ.range (fun _ => Iff.rfl) (baseGenerator σ j)
  rw [← h]
  exact (restrictedEmbedding_injective (phi := MulEquiv.refl C) σ.range (fun _ => Iff.rfl)).comp
    (freeToRestricted_injective C σ hσ hdisj)

/-- The image is exactly the subgroup generated by the original image and
the stable letter. This equality does not need the disjointness hypothesis. -/
theorem range_hom : (hom C σ).range =
    generatedWithStable (A := C) (B := C) (phi := MulEquiv.refl C) σ.range := by
  apply le_antisymm
  · rw [hom, FreeGroup.range_lift_eq_closure]
    rw [Subgroup.closure_le]
    rintro x ⟨i, rfl⟩
    refine Fin.lastCases ?_ (fun j => ?_) i
    · simp only [Fin.lastCases_last]
      exact Subgroup.subset_closure (Or.inr rfl)
    · simp only [Fin.lastCases_castSucc]
      apply Subgroup.subset_closure
      exact Or.inl ⟨σ (FreeGroup.of j), ⟨FreeGroup.of j, rfl⟩, rfl⟩
  · rw [generatedWithStable, Subgroup.closure_le]
    rintro x (hx | rfl)
    · rcases hx with ⟨g, ⟨w, rfl⟩, rfl⟩
      refine ⟨FreeGroup.map Fin.castSucc w, ?_⟩
      exact DFunLike.congr_fun (hom_comp_old C σ) w
    · exact ⟨FreeGroup.of (Fin.last n), hom_last C σ⟩

/-- The new free subgroup meets the original HNN base exactly in the
original free subgroup. -/
theorem range_hom_inf_base : (hom C σ).range ⊓ (centralizerOf C).range =
    σ.range.map (centralizerOf C) := by
  rw [range_hom]
  exact generatedWithStable_inf_base σ.range (fun _ => Iff.rfl)

end

end UniversalGroup.AdjoinFree
