module

public import Mathlib.GroupTheory.HNNExtension

@[expose] public section

/-!
Restricted HNN extensions and subgroup-intersection lemmas.
This module has no simulator or computability hypotheses.
-/

open Set

namespace UniversalGroup
namespace HNNLemmas

variable {G : Type*} [Group G]
variable {A B : Subgroup G} {phi : A ≃* B}

/-- An injective homomorphism identifies its domain with its range. -/
noncomputable def equivRangeOfInjective
    {H : Type*} [Group H] (f : H →* G) (hf : Function.Injective f) :
    H ≃* MonoidHom.range f :=
  MulEquiv.ofBijective f.rangeRestrict
    ⟨MonoidHom.rangeRestrict_injective_iff.mpr hf,
      f.rangeRestrict_surjective⟩

/-- Two injectively parametrized subgroups with the same parameter group are
canonically isomorphic. -/
noncomputable def rangeEquiv
    {H : Type*} [Group H] (f g : H →* G)
    (hf : Function.Injective f) (hg : Function.Injective g) :
    MonoidHom.range f ≃* MonoidHom.range g :=
  (equivRangeOfInjective f hf).symm.trans (equivRangeOfInjective g hg)

@[simp]
theorem rangeEquiv_apply_range
    {H : Type*} [Group H] (f g : H →* G)
    (hf : Function.Injective f) (hg : Function.Injective g) (x : H) :
    ((rangeEquiv f g hf hg ⟨f x, ⟨x, rfl⟩⟩ : MonoidHom.range g) : G) =
      g x := by
  change g ((equivRangeOfInjective f hf).symm ⟨f x, ⟨x, rfl⟩⟩) = g x
  have hy : (equivRangeOfInjective f hf).symm ⟨f x, ⟨x, rfl⟩⟩ = x := by
    apply hf
    exact congrArg Subtype.val
      ((equivRangeOfInjective f hf).apply_symm_apply ⟨f x, ⟨x, rfl⟩⟩)
  exact congrArg g hy

/-- The subgroup generated by an embedded subgroup and the stable letter. -/
def generatedWithStable (H : Subgroup G) :
    Subgroup (HNNExtension G A B phi) :=
  Subgroup.closure
    ((↑(H.map (HNNExtension.of (A := A) (B := B) (φ := phi))) :
        Set (HNNExtension G A B phi)) ∪
      {HNNExtension.t (A := A) (B := B) (φ := phi)})

/-! ## Transporting HNN extensions across an equivalence of HNN data -/

/-- A homomorphism between HNN extensions induced by equivalences of the
base groups and both associated subgroups.  The three compatibility
hypotheses say that the subgroup equivalences are the restrictions of the
base equivalence and intertwine the attaching maps. -/
def congrHom
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) :
    HNNExtension G A B phi →* HNNExtension G' A' B' φ' :=
  HNNExtension.lift
    ((HNNExtension.of (A := A') (B := B') (φ := φ')).comp e.toMonoidHom)
    (HNNExtension.t (A := A') (B := B') (φ := φ')) (by
      intro a
      have ht := HNNExtension.t_mul_of (φ := φ') (eA a)
      change
        HNNExtension.t * HNNExtension.of (e (a : G)) =
          HNNExtension.of (e (phi a : G)) * HNNExtension.t
      rw [← hA a, ← hB (phi a)]
      simpa [hφ a] using ht)

@[simp]
theorem congrHom_of
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) (g : G) :
    congrHom e eA eB hA hB hφ
        (HNNExtension.of (A := A) (B := B) (φ := phi) g) =
      HNNExtension.of (A := A') (B := B') (φ := φ') (e g) := by
  simp [congrHom]

@[simp]
theorem congrHom_t
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) :
    congrHom e eA eB hA hB hφ
        (HNNExtension.t (A := A) (B := B) (φ := phi)) =
      HNNExtension.t (A := A') (B := B') (φ := φ') := by
  simp [congrHom]

/-- Isomorphic HNN data give isomorphic HNN extensions, with the stable
letter fixed. -/
noncomputable def congr
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) :
    HNNExtension G A B phi ≃* HNNExtension G' A' B' φ' := by
  let hA' : ∀ a' : A', (eA.symm a' : G) = e.symm (a' : G') := by
    intro a'
    apply e.injective
    rw [e.apply_symm_apply, ← hA (eA.symm a'), eA.apply_symm_apply]
  let hB' : ∀ b' : B', (eB.symm b' : G) = e.symm (b' : G') := by
    intro b'
    apply e.injective
    rw [e.apply_symm_apply, ← hB (eB.symm b'), eB.apply_symm_apply]
  let hφ' : ∀ a' : A', eB.symm (φ' a') = phi (eA.symm a') := by
    intro a'
    apply eB.injective
    rw [eB.apply_symm_apply, hφ (eA.symm a'), eA.apply_symm_apply]
  let f := congrHom e eA eB hA hB hφ
  let g := congrHom e.symm eA.symm eB.symm hA' hB' hφ'
  refine
    { toFun := f
      invFun := g
      left_inv := ?_
      right_inv := ?_
      map_mul' := map_mul f }
  · intro x
    have hgf : g.comp f = MonoidHom.id _ := by
      apply HNNExtension.hom_ext
      · ext z
        simp [f, g]
      · simp [f, g]
    exact DFunLike.congr_fun hgf x
  · intro x
    have hfg : f.comp g = MonoidHom.id _ := by
      apply HNNExtension.hom_ext
      · ext z
        simp [f, g]
      · simp [f, g]
    exact DFunLike.congr_fun hfg x

/-!
The first intersection calculation is most conveniently proved by comparing
the ambient HNN extension with the HNN extension obtained by restricting both
associated subgroups to `H`.  The following definitions and lemmas implement
that comparison.  The construction and its basic API are public because the
same restricted embedding is also used to prove exact subgroup presentations
at later HNN stages; only the normal-form implementation remains private.
-/

def restrictedA (H : Subgroup G) : Subgroup H :=
  A.comap H.subtype

def restrictedB (H : Subgroup G) : Subgroup H :=
  B.comap H.subtype

def restrictedPhi (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    restrictedA (A := A) H ≃* restrictedB (B := B) H where
  toFun a :=
    ⟨⟨phi ⟨((a : H) : G), a.property⟩,
        (hphi ⟨((a : H) : G), a.property⟩).mp (a : H).property⟩,
      (phi ⟨((a : H) : G), a.property⟩).property⟩
  invFun b :=
    let bb : B := ⟨((b : H) : G), b.property⟩
    let aa : A := phi.symm bb
    ⟨⟨(aa : G), (hphi aa).mpr (by simp [bb, aa, (b : H).property])⟩,
      aa.property⟩
  left_inv a := by
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun x : A ↦ (x : G))
      (phi.symm_apply_apply ⟨((a : H) : G), a.property⟩)
  right_inv b := by
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun x : B ↦ (x : G))
      (phi.apply_symm_apply ⟨((b : H) : G), b.property⟩)
  map_mul' a b := by
    refine Subtype.ext (Subtype.ext ?_)
    change
      (phi
          (⟨((a : H) : G) * ((b : H) : G),
            A.mul_mem a.property b.property⟩ : A) : G) = _
    let aa : A := ⟨((a : H) : G), a.property⟩
    let bb : A := ⟨((b : H) : G), b.property⟩
    exact congrArg (fun x : B ↦ (x : G)) (map_mul phi aa bb)

def restrictedEmbedding (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    HNNExtension H (restrictedA (A := A) H) (restrictedB (B := B) H)
        (restrictedPhi H hphi) →*
      HNNExtension G A B phi :=
  HNNExtension.lift
    ((HNNExtension.of (A := A) (B := B) (φ := phi)).comp H.subtype)
    (HNNExtension.t (A := A) (B := B) (φ := phi)) (by
      intro a
      change HNNExtension.t * HNNExtension.of (((a : H) : G)) =
        HNNExtension.of
            ((((restrictedPhi H hphi) a : restrictedB (B := B) H) : H) : G) *
          HNNExtension.t
      simpa [restrictedPhi] using HNNExtension.t_mul_of
        (φ := phi) (⟨((a : H) : G), a.property⟩ : A))

@[simp]
theorem restrictedEmbedding_of (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) (h : H) :
    restrictedEmbedding H hphi (HNNExtension.of h) =
      HNNExtension.of (h : G) := by
  simp [restrictedEmbedding]

@[simp]
theorem restrictedEmbedding_t (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    restrictedEmbedding H hphi HNNExtension.t = HNNExtension.t := by
  simp [restrictedEmbedding]

theorem restrictedEmbedding_range (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    MonoidHom.range (restrictedEmbedding H hphi) =
      generatedWithStable (A := A) (B := B) (phi := phi) H := by
  apply le_antisymm
  · rintro x ⟨y, rfl⟩
    induction y using HNNExtension.induction_on with
    | of h =>
        apply Subgroup.subset_closure
        left
        exact ⟨h, h.property, by simp⟩
    | t =>
        apply Subgroup.subset_closure
        exact Or.inr (Set.mem_singleton _)
    | mul x y hx hy => simpa using Subgroup.mul_mem _ hx hy
    | inv x hx => simpa using Subgroup.inv_mem _ hx
  · unfold generatedWithStable
    rw [Subgroup.closure_le]
    rintro x (hx | rfl)
    · rcases hx with ⟨h, hh, rfl⟩
      exact ⟨HNNExtension.of (⟨h, hh⟩ : H), by simp⟩
    · exact ⟨HNNExtension.t, by simp⟩

private lemma mem_restricted_toSubgroup (H : Subgroup G) (u : ℤˣ) (h : H)
    (hh : (h : G) ∈ HNNExtension.toSubgroup A B u) :
    h ∈ HNNExtension.toSubgroup
      (restrictedA (A := A) H) (restrictedB (B := B) H) u := by
  rcases Int.units_eq_one_or u with rfl | rfl
  · change ((h : G) ∈ A)
    simpa using hh
  · change ((h : G) ∈ B)
    simpa using hh

private def mapRestrictedReducedWord (H : Subgroup G)
    (w : HNNExtension.NormalWord.ReducedWord H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :
    HNNExtension.NormalWord.ReducedWord G A B where
  head := (w.head : G)
  toList := w.toList.map (fun x ↦ (x.1, (x.2 : G)))
  chain := by
    rw [List.isChain_map]
    apply w.chain.imp
    intro a b hab hmem
    exact hab (mem_restricted_toSubgroup H a.1 a.2 hmem)

private lemma mapRestrictedReducedWord_prod (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    (w : HNNExtension.NormalWord.ReducedWord H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :
    (mapRestrictedReducedWord (A := A) (B := B) H w).prod phi =
      restrictedEmbedding H hphi (w.prod (restrictedPhi H hphi)) := by
  simp only [HNNExtension.NormalWord.ReducedWord.prod,
    mapRestrictedReducedWord, List.map_map, map_mul, map_list_prod]
  congr 1
  induction w.toList with
  | nil => simp
  | cons x xs ih =>
      simp only [List.map_cons, List.prod_cons, ih]
      simp [restrictedEmbedding]

private theorem restrictedEmbedding_preimage_base (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    (y : HNNExtension H (restrictedA (A := A) H) (restrictedB (B := B) H)
      (restrictedPhi H hphi))
    (hy : restrictedEmbedding H hphi y ∈
      MonoidHom.range (HNNExtension.of (A := A) (B := B) (φ := phi))) :
    ∃ h : H, y = HNNExtension.of h := by
  let psi := restrictedPhi H hphi
  let : Nonempty (HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :=
    HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
  let d : HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H) :=
    Classical.choice inferInstance
  let w : HNNExtension.NormalWord d :=
    (HNNExtension.NormalWord.equiv psi d) y
  have hwy : w.toReducedWord.prod psi = y :=
    (HNNExtension.NormalWord.equiv psi d).symm_apply_apply y
  have hmapped :
      (mapRestrictedReducedWord (A := A) (B := B) H w.toReducedWord).prod phi ∈
        MonoidHom.range (HNNExtension.of (A := A) (B := B) (φ := phi)) := by
    rw [mapRestrictedReducedWord_prod H hphi, hwy]
    exact hy
  have hnilmap :=
    HNNExtension.ReducedWord.toList_eq_nil_of_mem_of_range phi
      (mapRestrictedReducedWord (A := A) (B := B) H w.toReducedWord) hmapped
  have hnil : w.toList = [] := by
    simpa [mapRestrictedReducedWord] using hnilmap
  refine ⟨w.head, ?_⟩
  rw [← hwy]
  simp [HNNExtension.NormalWord.ReducedWord.prod, hnil]

/-- The canonical homomorphism from an HNN extension restricted to a
subgroup `H` into the ambient HNN extension is injective.  This is the
injectivity assertion in the restricted-HNN lemma: a non-base reduced word
remains reduced in the ambient extension, while injectivity on the base is
`HNNExtension.of_injective`. -/
theorem restrictedEmbedding_injective (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    Function.Injective (restrictedEmbedding H hphi) := by
  apply (injective_iff_map_eq_one (restrictedEmbedding H hphi)).mpr
  intro y hy
  have hybase : restrictedEmbedding H hphi y ∈
      MonoidHom.range
        (HNNExtension.of (A := A) (B := B) (φ := phi)) := by
    refine ⟨1, ?_⟩
    simpa using hy.symm
  rcases restrictedEmbedding_preimage_base H hphi y hybase with ⟨h, rfl⟩
  rw [restrictedEmbedding_of] at hy
  have hh : (h : G) = 1 := by
    apply HNNExtension.of_injective phi
    simpa using hy
  have hH : h = 1 := by
    apply Subtype.ext
    exact hh
  simp [hH]

/-- The restricted HNN extension, identified with the subgroup generated by
the embedded copy of `H` and the ambient stable letter.  This is the exact
subgroup-presentation form of Appendix A.1 used by the compression stages. -/
noncomputable def restrictedEquivGeneratedWithStable (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    HNNExtension H (restrictedA (A := A) H) (restrictedB (B := B) H)
        (restrictedPhi H hphi) ≃*
      generatedWithStable (A := A) (B := B) (phi := phi) H :=
  (MonoidHom.ofInjective (restrictedEmbedding_injective H hphi)).trans
    (MulEquiv.subgroupCongr (restrictedEmbedding_range H hphi))

@[simp]
theorem restrictedEquivGeneratedWithStable_coe (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    (x : HNNExtension H (restrictedA (A := A) H)
      (restrictedB (B := B) H) (restrictedPhi H hphi)) :
    ((restrictedEquivGeneratedWithStable H hphi x :
        generatedWithStable (A := A) (B := B) (phi := phi) H) :
      HNNExtension G A B phi) = restrictedEmbedding H hphi x := by
  simp [restrictedEquivGeneratedWithStable,
    MonoidHom.ofInjective_apply, MulEquiv.subgroupCongr_apply]

/--
Restricted-HNN intersection lemma (Appendix A.1), stated in the form used by
the tower calculations.
-/
theorem generatedWithStable_inf_base
    (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    generatedWithStable (A := A) (B := B) (phi := phi) H ⊓
        MonoidHom.range (HNNExtension.of (A := A) (B := B) (φ := phi)) =
      H.map (HNNExtension.of (A := A) (B := B) (φ := phi)) := by
  ext x
  constructor
  · intro hx
    have hxg : x ∈ generatedWithStable (A := A) (B := B) (phi := phi) H := hx.1
    rw [← restrictedEmbedding_range H hphi] at hxg
    rcases hxg with ⟨y, hy⟩
    rcases restrictedEmbedding_preimage_base H hphi y (hy ▸ hx.2) with ⟨h, rfl⟩
    rw [restrictedEmbedding_of] at hy
    exact ⟨h, h.property, hy⟩
  · rintro ⟨g, hg, rfl⟩
    constructor
    · apply Subgroup.subset_closure
      exact Or.inl ⟨g, hg, rfl⟩
    · exact ⟨g, rfl⟩

/-- Every element of the subgroup generated by an embedded subgroup `H` and
the stable letter admits an ambient HNN-reduced word all of whose base
coefficients lie in `H`.  The compatibility hypothesis is exactly what is
needed to form the restricted HNN extension over `H`.

This is the normal-form existence statement used for Borisov's irreducible
`{c,d}` and `{c,e}` contexts. -/
theorem exists_reducedWord_of_mem_generatedWithStable
    (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    {x : HNNExtension G A B phi}
    (hx : x ∈ generatedWithStable (A := A) (B := B) (phi := phi) H) :
    ∃ w : HNNExtension.NormalWord.ReducedWord G A B,
      w.prod phi = x ∧ w.head ∈ H ∧ ∀ p ∈ w.toList, p.2 ∈ H := by
  rw [← restrictedEmbedding_range H hphi] at hx
  rcases hx with ⟨y, rfl⟩
  let psi := restrictedPhi H hphi
  let : Nonempty (HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :=
    HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
  let d : HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H) :=
    Classical.choice inferInstance
  let w : HNNExtension.NormalWord d :=
    (HNNExtension.NormalWord.equiv psi d) y
  let wm := mapRestrictedReducedWord (A := A) (B := B) H w.toReducedWord
  refine ⟨wm, ?_, ?_, ?_⟩
  · rw [mapRestrictedReducedWord_prod H hphi]
    exact congrArg (restrictedEmbedding H hphi)
      ((HNNExtension.NormalWord.equiv psi d).symm_apply_apply y)
  · exact w.head.property
  · intro p hp
    dsimp [wm, mapRestrictedReducedWord] at hp
    rw [List.mem_map] at hp
    rcases hp with ⟨q, hq, rfl⟩
    exact q.2.property

/-- A centralizer HNN extension. -/
abbrev CentralizerHNN (G : Type*) [Group G] (C : Subgroup G) :=
  HNNExtension G C C (MulEquiv.refl C)

def centralizerOf (C : Subgroup G) : G →* CentralizerHNN G C :=
  HNNExtension.of

def centralizerStable (C : Subgroup G) : CentralizerHNN G C :=
  HNNExtension.t

/-- In a centralizer HNN extension, an element of the base group commutes
with the stable letter exactly when it belongs to the centralized subgroup.
This is the two-syllable form of Britton's lemma used at Borisov's final
`k`-stage. -/
theorem centralizerOf_commute_stable_iff (C : Subgroup G) (g : G) :
    Commute (centralizerOf C g) (centralizerStable C) ↔ g ∈ C := by
  constructor
  · intro hcomm
    let w₁ : HNNExtension.NormalWord.ReducedWord G C C :=
      { head := g
        toList := [(1, 1)]
        chain := List.isChain_singleton _ }
    let w₂ : HNNExtension.NormalWord.ReducedWord G C C :=
      { head := 1
        toList := [(1, g)]
        chain := List.isChain_singleton _ }
    have hprod : w₁.prod (MulEquiv.refl C) = w₂.prod (MulEquiv.refl C) := by
      simpa [w₁, w₂, HNNExtension.NormalWord.ReducedWord.prod,
        centralizerOf, centralizerStable] using hcomm.eq
    have hcoset :=
      (HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
        (MulEquiv.refl C) hprod).2 (1 : ℤˣ) (by simp [w₁])
    have hinv : g⁻¹ ∈ C := by simpa [w₁, w₂] using hcoset
    simpa using C.inv_mem hinv
  · intro hg
    let c : C := ⟨g, hg⟩
    have h := HNNExtension.t_mul_of (φ := MulEquiv.refl C) c
    show centralizerOf C g * centralizerStable C =
      centralizerStable C * centralizerOf C g
    simpa [centralizerOf, centralizerStable, c] using h.symm

/-- The subgroup generated by `H` and one additional element `u`. -/
def generatedWith
    {E : Type*} [Group E] (H : Subgroup E) (u : E) : Subgroup E :=
  Subgroup.closure ((H : Set E) ∪ {u})

private theorem centralizer_generatedWith_reducedWord
    (C D : Subgroup G) {x : CentralizerHNN G C}
    (hx : x ∈ generatedWith (D.map (centralizerOf C)) (centralizerStable C)) :
    ∃ w : HNNExtension.NormalWord.ReducedWord G C C,
      w.prod (MulEquiv.refl C) = x ∧ w.head ∈ D ∧
        ∀ p ∈ w.toList, p.2 ∈ D := by
  have hphi : ∀ c : C,
      (c : G) ∈ D ↔ ((MulEquiv.refl C) c : G) ∈ D := by simp
  apply exists_reducedWord_of_mem_generatedWithStable D hphi
  simpa [generatedWith, generatedWithStable, centralizerOf, centralizerStable]
    using hx

/-- The product set `Delta * B₀ * Delta` appearing in Appendix A.4. -/
def deltaDoubleCoset (Delta B₀ : Subgroup G) : Set G :=
  {x | ∃ d₁ ∈ Delta, ∃ b ∈ B₀, ∃ d₂ ∈ Delta, x = d₁ * b * d₂}

private lemma centralizer_of_mul_tpow (Delta : Subgroup G) (u : ℤˣ) (d : Delta) :
    (HNNExtension.of (d : G) : CentralizerHNN G Delta) *
        HNNExtension.t ^ (u : ℤ) =
      HNNExtension.t ^ (u : ℤ) * HNNExtension.of (d : G) := by
  rcases Int.units_eq_one_or u with rfl | rfl
  · simpa using HNNExtension.of_mul_t (φ := MulEquiv.refl Delta) d
  · simpa using HNNExtension.of_mul_inv_t (φ := MulEquiv.refl Delta) d

private def centralizerReducedWord (Delta : Subgroup G) (g : G)
    (l : List (ℤˣ × G))
    (chain : l.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1)) :
    HNNExtension.NormalWord.ReducedWord G Delta Delta :=
  ⟨g, l, chain⟩

private lemma centralizer_tail_prod_eq (Delta : Subgroup G)
    (g₁ g₂ a b : G) (u : ℤˣ) (l₁ l₂ : List (ℤˣ × G))
    (c₁ : ((u, a) :: l₁).IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (c₂ : ((u, b) :: l₂).IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (hd : g₁⁻¹ * g₂ ∈ Delta)
    (heq :
      (centralizerReducedWord Delta g₁ ((u, a) :: l₁) c₁).prod
          (MulEquiv.refl Delta) =
        (centralizerReducedWord Delta g₂ ((u, b) :: l₂) c₂).prod
          (MulEquiv.refl Delta)) :
    (centralizerReducedWord Delta a l₁ (List.isChain_cons.1 c₁).2).prod
        (MulEquiv.refl Delta) =
      (centralizerReducedWord Delta ((g₁⁻¹ * g₂) * b) l₂
        (List.isChain_cons.1 c₂).2).prod (MulEquiv.refl Delta) := by
  let d : Delta := ⟨g₁⁻¹ * g₂, hd⟩
  have hc := centralizer_of_mul_tpow Delta u d
  dsimp [centralizerReducedWord, HNNExtension.NormalWord.ReducedWord.prod] at heq ⊢
  have heq' := congrArg
    (fun x : CentralizerHNN G Delta =>
      (HNNExtension.of g₁ * HNNExtension.t ^ (u : ℤ))⁻¹ * x) heq
  simp only [mul_inv_rev] at heq'
  simp [mul_assoc] at heq'
  rw [← mul_assoc (HNNExtension.of g₁)⁻¹ (HNNExtension.of g₂) _] at heq'
  rw [← map_inv, ← map_mul] at heq'
  rw [← mul_assoc (HNNExtension.of (g₁⁻¹ * g₂))
    (HNNExtension.t ^ (u : ℤ)) _] at heq'
  rw [hc] at heq'
  change _ = HNNExtension.of ((d : G) * b) * _
  simpa [mul_assoc] using heq'

private lemma centralizer_toSubgroup_self (Delta : Subgroup G) (u : ℤˣ) :
    HNNExtension.toSubgroup Delta Delta u = Delta := by
  rcases Int.units_eq_one_or u with rfl | rfl <;> rfl

/-!
For two equal reduced words in a centralizer HNN extension, comparison of
their first base coefficients gives an element of `Delta`.  Commuting that
element through the first stable letter lets us repeat the argument on the
tails.  This is the coefficient-by-coefficient form of the normal-form
argument needed in Appendix A.4.
-/
private lemma centralizer_reduced_coefficients
    (Delta L B₀ C : Subgroup G)
    (hinter : (L : Set G) ∩ deltaDoubleCoset Delta B₀ = (C : Set G))
    (g₁ g₂ : G) (l₁ l₂ : List (ℤˣ × G))
    (c₁ : l₁.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (c₂ : l₂.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (hprod : (centralizerReducedWord Delta g₁ l₁ c₁).prod
        (MulEquiv.refl Delta) =
      (centralizerReducedWord Delta g₂ l₂ c₂).prod
        (MulEquiv.refl Delta))
    (hg₁ : g₁ ∈ L) (hl₁ : ∀ x ∈ l₁, x.2 ∈ L)
    (hg₂ : g₂ ∈ deltaDoubleCoset Delta B₀)
    (hl₂ : ∀ x ∈ l₂, x.2 ∈ B₀) :
    g₁ ∈ C ∧ ∀ x ∈ l₁, x.2 ∈ C := by
  induction l₁ generalizing g₁ g₂ l₂ with
  | nil =>
      have hmaps :=
        (HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
          (MulEquiv.refl Delta) hprod).1
      cases l₂ with
      | cons q qs => simp [centralizerReducedWord] at hmaps
      | nil =>
          have heqOf : HNNExtension.of g₁ =
              (HNNExtension.of g₂ : CentralizerHNN G Delta) := by
            simpa [centralizerReducedWord,
              HNNExtension.NormalWord.ReducedWord.prod] using hprod
          have hg : g₁ = g₂ := HNNExtension.of_injective
            (A := Delta) (B := Delta) (φ := MulEquiv.refl Delta) heqOf
          have hdc : g₁ ∈ deltaDoubleCoset Delta B₀ := by
            simpa [hg] using hg₂
          have hgC : g₁ ∈ C :=
            (Set.ext_iff.mp hinter g₁).mp ⟨hg₁, hdc⟩
          exact ⟨hgC, by simp⟩
  | cons p ps ih =>
      have hcompare := HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
        (MulEquiv.refl Delta) hprod
      cases l₂ with
      | nil => simp [centralizerReducedWord] at hcompare
      | cons q qs =>
          rcases p with ⟨u, a⟩
          rcases q with ⟨v, b⟩
          have hmaps := hcompare.1
          change u :: ps.map Prod.fst = v :: qs.map Prod.fst at hmaps
          have huv : u = v := (List.cons.inj hmaps).1
          subst v
          have hd : g₁⁻¹ * g₂ ∈ Delta := by
            have hd' := hcompare.2 u (by simp [centralizerReducedWord])
            change g₁⁻¹ * g₂ ∈
              HNNExtension.toSubgroup Delta Delta (-u) at hd'
            simpa [centralizer_toSubgroup_self] using hd'
          let d : Delta := ⟨g₁⁻¹ * g₂, hd⟩
          have hdc : g₁ ∈ deltaDoubleCoset Delta B₀ := by
            rcases hg₂ with ⟨d₁, hd₁, b₀, hb₀, d₂, hd₂, rfl⟩
            refine ⟨d₁, hd₁, b₀, hb₀, d₂ * d⁻¹,
              Delta.mul_mem hd₂ (Delta.inv_mem hd), ?_⟩
            dsimp [d]
            simp [mul_assoc]
          have hgC : g₁ ∈ C :=
            (Set.ext_iff.mp hinter g₁).mp ⟨hg₁, hdc⟩
          have hc₁tail := (List.isChain_cons.1 c₁).2
          have hc₂tail := (List.isChain_cons.1 c₂).2
          have htailprod := centralizer_tail_prod_eq Delta
            g₁ g₂ a b u ps qs c₁ c₂ hd hprod
          have haL : a ∈ L := hl₁ (u, a) (by simp)
          have hbB : b ∈ B₀ := hl₂ (u, b) (by simp)
          have htailHead : (d : G) * b ∈ deltaDoubleCoset Delta B₀ :=
            ⟨d, hd, b, hbB, 1, Delta.one_mem, by simp⟩
          have htail := ih a ((d : G) * b) qs hc₁tail hc₂tail htailprod haL
            (by
              intro x hx
              exact hl₁ x (List.mem_cons_of_mem _ hx))
            htailHead
            (by
              intro x hx
              exact hl₂ x (List.mem_cons_of_mem _ hx))
          refine ⟨hgC, ?_⟩
          intro x hx
          rcases List.mem_cons.1 hx with rfl | hx
          · exact htail.1
          · exact htail.2 x hx

private lemma exists_reducedWord_for_generatedWith
    (Delta H : Subgroup G)
    {x : CentralizerHNN G Delta}
    (hx : x ∈ generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta)) :
    ∃ w : HNNExtension.NormalWord.ReducedWord G Delta Delta,
      w.prod (MulEquiv.refl Delta) = x ∧ w.head ∈ H ∧
        ∀ p ∈ w.toList, p.2 ∈ H :=
  centralizer_generatedWith_reducedWord Delta H hx

private lemma reducedWord_prod_mem_generatedWith
    (Delta H : Subgroup G)
    (w : HNNExtension.NormalWord.ReducedWord G Delta Delta)
    (hhead : w.head ∈ H) (hlist : ∀ p ∈ w.toList, p.2 ∈ H) :
    w.prod (MulEquiv.refl Delta) ∈
      generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta) := by
  let K := generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta)
  have hof : HNNExtension.of w.head ∈ K := by
    apply Subgroup.subset_closure
    exact Or.inl ⟨w.head, hhead, rfl⟩
  have ht : (HNNExtension.t : CentralizerHNN G Delta) ∈ K := by
    apply Subgroup.subset_closure
    exact Or.inr rfl
  have hprodListAux : ∀ l : List (ℤˣ × G),
      (∀ p ∈ l, p.2 ∈ H) →
      (l.map (fun p => HNNExtension.t ^ (p.1 : ℤ) * HNNExtension.of p.2)).prod ∈ K := by
    intro l hl
    induction l with
    | nil => simp [K]
    | cons p ps ih =>
        rw [List.map_cons, List.prod_cons]
        apply K.mul_mem
        · apply K.mul_mem
          · exact K.zpow_mem ht _
          · apply Subgroup.subset_closure
            exact Or.inl ⟨p.2, hl p (by simp), rfl⟩
        · exact ih (by
            intro q hq
            exact hl q (List.mem_cons_of_mem _ hq))
  exact K.mul_mem hof (hprodListAux w.toList hlist)

private lemma generatedWith_mono (Delta : Subgroup G) {H K : Subgroup G}
    (hHK : H ≤ K) :
    generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta) ≤
      generatedWith (K.map (centralizerOf Delta)) (centralizerStable Delta) := by
  unfold generatedWith
  apply Subgroup.closure_mono
  exact Set.union_subset_union (Subgroup.map_mono hHK) Set.Subset.rfl

/-- Appendix A.4: intersection inside a centralizer HNN extension. -/
theorem centralizer_intersection_of_doubleCoset
    (Delta L B₀ C : Subgroup G)
    (hCL : C ≤ L) (hCB₀ : C ≤ B₀)
    (hinter : (L : Set G) ∩ deltaDoubleCoset Delta B₀ = (C : Set G)) :
    generatedWith (L.map (centralizerOf Delta)) (centralizerStable Delta) ⊓
        generatedWith (B₀.map (centralizerOf Delta)) (centralizerStable Delta) =
      generatedWith (C.map (centralizerOf Delta)) (centralizerStable Delta) := by
  ext x
  constructor
  · intro hx
    rcases exists_reducedWord_for_generatedWith Delta L hx.1 with
      ⟨wL, hwL, hwLhead, hwLlist⟩
    rcases exists_reducedWord_for_generatedWith Delta B₀ hx.2 with
      ⟨wB, hwB, hwBhead, hwBlist⟩
    have hwBhead' : wB.head ∈ deltaDoubleCoset Delta B₀ :=
      ⟨1, Delta.one_mem, wB.head, hwBhead, 1, Delta.one_mem, by simp⟩
    have hcoeff := centralizer_reduced_coefficients Delta L B₀ C
      hinter
      wL.head wB.head wL.toList wB.toList wL.chain wB.chain
      (hwL.trans hwB.symm) hwLhead hwLlist hwBhead' hwBlist
    have hm := reducedWord_prod_mem_generatedWith Delta C wL hcoeff.1 hcoeff.2
    rwa [hwL] at hm
  · intro hx
    exact ⟨generatedWith_mono Delta hCL hx, generatedWith_mono Delta hCB₀ hx⟩

/-- If one base subgroup contains the subgroup centralized by the stable
letter, adjoining that letter commutes with taking its intersection with
any other base subgroup. -/
theorem centralizer_intersection_of_le
    (Delta L B : Subgroup G) (hDB : Delta ≤ B) :
    generatedWithStable (A := Delta) (B := Delta) (phi := MulEquiv.refl Delta) L ⊓
      generatedWithStable (A := Delta) (B := Delta) (phi := MulEquiv.refl Delta) B =
    generatedWithStable (A := Delta) (B := Delta) (phi := MulEquiv.refl Delta) (L ⊓ B) := by
  apply centralizer_intersection_of_doubleCoset Delta L B (L ⊓ B) inf_le_left inf_le_right
  ext x
  constructor
  · rintro ⟨hxL, a, ha, b, hb, c, hc, rfl⟩
    exact ⟨hxL, B.mul_mem (B.mul_mem (hDB ha) hb) (hDB hc)⟩
  · rintro ⟨hxL, hxB⟩
    exact ⟨hxL, 1, Delta.one_mem, x, hxB, 1, Delta.one_mem, by simp⟩

end HNNLemmas
end UniversalGroup
