module

public import UniversalGroup.Higman.Benign
public import UniversalGroup.Higman.PositiveKernel

@[expose] public section

/-!
# The diagonal subgroup quotient in Higman's embedding argument

For a set `W ⊆ F` containing `1`, the diagonal words `w T f⁻¹ w⁻¹ f`
include `T`. Killing them therefore kills `T` and makes `f` centralize
the subgroup generated by `W`, giving the centralizer HNN presentation.
-/

namespace UniversalGroup.HigmanDelta

noncomputable section

universe u
variable {F : Type u} [Group F]

abbrev Base (F : Type u) [Group F] := Monoid.Coprod F (FreeGroup (Fin 2))

def of : F →* Base F := Monoid.Coprod.inl

def letter (i : Fin 2) : Base F := Monoid.Coprod.inr (FreeGroup.of i)

def delta (w : F) : Base F :=
  of w * letter 1 * (letter 0)⁻¹ * (of w)⁻¹ * letter 0

/-- The diagonal subgroup generated by the specified accepted set. -/
def subgroup (W : Set F) : Subgroup (Base F) :=
  Subgroup.closure (delta '' W)

abbrev Quotient (W : Set F) :=
  Base F ⧸ Subgroup.normalClosure (subgroup W : Set (Base F))

def quotient (W : Set F) : Base F →* Quotient W := QuotientGroup.mk' _

theorem quotient_delta (W : Set F) (w : W) : quotient W (delta (w : F)) = 1 :=
  (QuotientGroup.eq_one_iff _).mpr
    (Subgroup.subset_normalClosure (Subgroup.subset_closure ⟨w, w.property, rfl⟩))

@[simp] theorem delta_one : delta (1 : F) = letter 1 := by simp [delta]

@[simp] theorem quotient_letter_one (W : Set F) (h1 : (1 : F) ∈ W) : quotient W (letter 1) = 1 := by
  simpa using quotient_delta W ⟨1, h1⟩

private theorem quotient_commute_generator (W : Set F) (h1 : (1 : F) ∈ W) (w : W) :
    Commute (quotient W (of (w : F))) (quotient W (letter 0)) := by
  have h := quotient_delta W w
  simp only [delta, map_mul, map_inv, quotient_letter_one W h1, mul_one] at h
  have hh := congrArg (fun z => z * (quotient W (letter 0))⁻¹ * quotient W (of (w : F))) h
  have he : quotient W (of (w : F)) * (quotient W (letter 0))⁻¹ =
      (quotient W (letter 0))⁻¹ * quotient W (of (w : F)) := by
    simpa only [mul_assoc, mul_inv_cancel, inv_mul_cancel, mul_one, one_mul] using hh
  exact Commute.inv_right_iff.mp ((commute_iff_eq _ _).mpr he)

/-- The diagonal equations force the stable letter to commute with
all of the subgroup generated by the accepted set. -/
theorem quotient_commute (W : Set F) (h1 : (1 : F) ∈ W) (w : Subgroup.closure W) :
    Commute (quotient W (of (w : F))) (quotient W (letter 0)) := by
  rcases w with ⟨w, hw⟩
  change Commute (quotient W (of w)) (quotient W (letter 0))
  induction hw using Subgroup.closure_induction with
  | mem g hg => exact quotient_commute_generator W h1 ⟨g, hg⟩
  | one => simp
  | mul a b ha hb iha ihb => simpa only [map_mul] using iha.mul_left ihb
  | inv a ha iha => simpa only [map_inv] using iha.inv_left

def rawToHNN (W : Set F) : Base F →* HNNLemmas.CentralizerHNN F (Subgroup.closure W) :=
  Monoid.Coprod.lift (HNNLemmas.centralizerOf (Subgroup.closure W))
    (FreeGroup.lift (fun i : Fin 2 => if i = 0 then HNNLemmas.centralizerStable (Subgroup.closure W) else 1))

private theorem rawToHNN_of (W : Set F) (w : F) :
    rawToHNN W (of w) = HNNLemmas.centralizerOf (Subgroup.closure W) w := by
  exact Monoid.Coprod.lift_apply_inl _ _ _

private theorem rawToHNN_letter (W : Set F) (i : Fin 2) :
    rawToHNN W (letter i) = if i = 0 then HNNLemmas.centralizerStable (Subgroup.closure W) else 1 := by
  change Monoid.Coprod.lift _ _ (Monoid.Coprod.inr (FreeGroup.of i)) = _
  rw [Monoid.Coprod.lift_apply_inr, FreeGroup.lift_apply_of]

private theorem rawToHNN_delta (W : Set F) (w : W) :
    rawToHNN W (delta (w : F)) = 1 := by
  have hc := (HNNLemmas.centralizerOf_commute_stable_iff (Subgroup.closure W) (w : F)).mpr (Subgroup.subset_closure w.property)
  simp only [delta, map_mul, map_inv, rawToHNN_of, rawToHNN_letter]
  simp only [show (1 : Fin 2) ≠ 0 by decide, ↓reduceIte, mul_one]
  rw [hc.inv_right.eq]
  group

theorem rawToHNN_kills (W : Set F) :
    Subgroup.normalClosure (subgroup W : Set (Base F)) ≤ (rawToHNN W).ker := by
  apply Subgroup.normalClosure_le_normal
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨w, hw, rfl⟩
  exact rawToHNN_delta W ⟨w, hw⟩

/-- The diagonal quotient maps to the centralizer HNN group. -/
def toHNN (W : Set F) : Quotient W →* HNNLemmas.CentralizerHNN F (Subgroup.closure W) :=
  QuotientGroup.lift _ (rawToHNN W) (rawToHNN_kills W)

@[simp] theorem toHNN_quotient (W : Set F) (x : Base F) :
    toHNN W (quotient W x) = rawToHNN W x := rfl

/-- The converse map uses the surviving free letter as stable letter. -/
def fromHNN (W : Set F) (h1 : (1 : F) ∈ W) : HNNLemmas.CentralizerHNN F (Subgroup.closure W) →* Quotient W :=
  HNNExtension.lift ((quotient W).comp of) (quotient W (letter 0))
    (fun w => (quotient_commute W h1 w).eq.symm)

@[simp] theorem fromHNN_of (W : Set F) (h1 : (1 : F) ∈ W) (w : F) :
    fromHNN W h1 (HNNLemmas.centralizerOf (Subgroup.closure W) w) = quotient W (of w) :=
  HNNExtension.lift_of _ _ _ _

@[simp] theorem fromHNN_stable (W : Set F) (h1 : (1 : F) ∈ W) :
    fromHNN W h1 (HNNLemmas.centralizerStable (Subgroup.closure W)) = quotient W (letter 0) :=
  HNNExtension.lift_t _ _ _

theorem left_inverse (W : Set F) (h1 : (1 : F) ∈ W) :
    (fromHNN W h1).comp (toHNN W) = MonoidHom.id (Quotient W) := by
  apply (MonoidHom.cancel_right (QuotientGroup.mk'_surjective _)).mp
  apply Monoid.Coprod.hom_ext
  · ext w
    change fromHNN W h1 (rawToHNN W (of w)) = quotient W (of w)
    rw [rawToHNN_of, fromHNN_of]
  · apply FreeGroup.ext_hom
    intro i
    change fromHNN W h1 (rawToHNN W (letter i)) = quotient W (letter i)
    rw [rawToHNN_letter]
    fin_cases i
    · change fromHNN W h1 (if (0 : Fin 2) = 0 then HNNLemmas.centralizerStable (Subgroup.closure W) else 1) = _
      simp
    · change fromHNN W h1 (if (1 : Fin 2) = 0 then HNNLemmas.centralizerStable (Subgroup.closure W) else 1) = _
      simp [quotient_letter_one W h1]

theorem right_inverse (W : Set F) (h1 : (1 : F) ∈ W) :
    (toHNN W).comp (fromHNN W h1) = MonoidHom.id (HNNLemmas.CentralizerHNN F (Subgroup.closure W)) := by
  apply HNNExtension.hom_ext
  · ext w
    change toHNN W (fromHNN W h1 (HNNLemmas.centralizerOf (Subgroup.closure W) w)) = HNNLemmas.centralizerOf (Subgroup.closure W) w
    rw [fromHNN_of, toHNN_quotient, rawToHNN_of]
  · change toHNN W (fromHNN W h1 (HNNLemmas.centralizerStable (Subgroup.closure W))) = HNNLemmas.centralizerStable (Subgroup.closure W)
    rw [fromHNN_stable, toHNN_quotient, rawToHNN_letter]
    simp

/-- The exact presentation comparison. -/
def equiv (W : Set F) (h1 : (1 : F) ∈ W) : Quotient W ≃* HNNLemmas.CentralizerHNN F (Subgroup.closure W) :=
  { toHNN W with
    invFun := fromHNN W h1
    left_inv := DFunLike.congr_fun (left_inverse W h1)
    right_inv := DFunLike.congr_fun (right_inverse W h1) }

/-- Benignity of the diagonal subgroup implies benignity of the input
subgroup. This packages two applications of Higman's final construction. -/
theorem benign_of_diagonal [Group.IsFinitelyPresented F] (W : Set F) (h1 : (1 : F) ∈ W)
    (h : HigmanBenign.Benign (subgroup W)) : HigmanBenign.Benign (Subgroup.closure W) := by
  obtain ⟨K, instK, hK, e, he⟩ := HigmanBenign.normalClosure_quotient_embedsInFP (subgroup W) h
  obtain ⟨_, fF, hfF, _⟩ := (inferInstance : Group.IsFinitelyPresented F).out
  let : Group.FG F := Group.fg_of_surjective hfF
  apply HigmanBenign.benign_of_centralizer (Subgroup.closure W)
  exact ⟨K, instK, hK, e.comp (equiv W h1).symm.toMonoidHom, he.comp (equiv W h1).symm.injective⟩

/-- A form with the generated subgroup named separately. -/
theorem benign_of_diagonal_eq [Group.IsFinitelyPresented F]
    (W : Set F) (h1 : (1 : F) ∈ W) (N : Subgroup F)
    (hN : Subgroup.closure W = N) (h : HigmanBenign.Benign (subgroup W)) :
    HigmanBenign.Benign N := by
  rw [← hN]
  exact benign_of_diagonal W h1 h


@[simp] theorem equiv_quotient_of (W : Set F) (h1 : (1 : F) ∈ W) (w : F) :
    equiv W h1 (quotient W (of w)) = HNNLemmas.centralizerOf (Subgroup.closure W) w := by
  exact rawToHNN_of W w

@[simp] theorem equiv_quotient_letter_zero (W : Set F) (h1 : (1 : F) ∈ W) :
    equiv W h1 (quotient W (letter 0)) = HNNLemmas.centralizerStable (Subgroup.closure W) := by
  exact (rawToHNN_letter W 0).trans (ite_eq_left rfl)

/-- The algebraic end of the positive-language route: it is enough to
make the diagonal subgroup on positive kernel words benign. -/
theorem benign_kernel_of_positive_diagonal {α : Type u} [Finite α]
    {G : Type*} [Group G] (π : FreeGroup α →* G)
    (hpos : ∀ i : α, ∃ w : List α,
      π (PositiveKernel.positive w) = (π (FreeGroup.of i))⁻¹)
    (h : HigmanBenign.Benign (subgroup (PositiveKernel.elements π))) :
    HigmanBenign.Benign π.ker :=
  benign_of_diagonal_eq (PositiveKernel.elements π) (PositiveKernel.one_mem_elements π)
    π.ker (PositiveKernel.subgroup_eq_ker π hpos) h

/-- With a surjective generating map, the same diagonal hypothesis embeds
the target group itself in a finitely presented group. -/
theorem embedsInFP_of_positive_diagonal {α : Type u} [Finite α]
    {G : Type u} [Group G] (π : FreeGroup α →* G) (hπ : Function.Surjective π)
    (hpos : ∀ i : α, ∃ w : List α,
      π (PositiveKernel.positive w) = (π (FreeGroup.of i))⁻¹)
    (h : HigmanBenign.Benign (subgroup (PositiveKernel.elements π))) :
    HigmanBenign.EmbedsInFP G := by
  have hker := benign_kernel_of_positive_diagonal π hpos h
  obtain ⟨K, instK, hK, e, he⟩ := HigmanBenign.quotient_embedsInFP π.ker hker
  let q := QuotientGroup.quotientKerEquivOfSurjective π hπ
  exact ⟨K, instK, hK, e.comp q.symm.toMonoidHom, he.comp q.symm.injective⟩

end
end UniversalGroup.HigmanDelta
