module

public import UniversalGroup.Foundations.Presentation

@[expose] public section

/-!
# Positive words generate the kernel when inverses have positive spellings

If every generator's inverse has a positive representative in the target,
the positive words equal to one generate the entire kernel as a subgroup,
not merely as a normal subgroup.
-/

namespace UniversalGroup.PositiveKernel

variable {α : Type*} {G : Type*} [Group G]

/-- Evaluate an unsigned word in the free group. -/
def positive (w : List α) : FreeGroup α := (w.map FreeGroup.of).prod

@[simp] theorem positive_nil : positive ([] : List α) = 1 := rfl
@[simp] theorem positive_cons (a : α) (w : List α) :
    positive (a :: w) = FreeGroup.of a * positive w := rfl
@[simp] theorem positive_append (u v : List α) :
    positive (u ++ v) = positive u * positive v := by simp [positive]
@[simp] theorem positive_singleton (a : α) : positive [a] = FreeGroup.of a := by simp

/-- Positive elements of the kernel. -/
def elements (π : FreeGroup α →* G) : Set (FreeGroup α) :=
  {g | ∃ w : List α, positive w = g ∧ π g = 1}

/-- The empty positive word supplies the identity. -/
theorem one_mem_elements (π : FreeGroup α →* G) : (1 : FreeGroup α) ∈ elements π :=
  ⟨[], rfl, map_one π⟩

/-- Unsigned and signed word evaluation agree for all-positive signs. -/
theorem positive_eq_mk (w : List α) :
    positive w = FreeGroup.mk (w.map (fun a => (a, true))) := by
  induction w with
  | nil => rfl
  | cons a w ih =>
      rw [positive_cons, ih]
      rfl

/-- The subgroup generated by positive kernel words. -/
def subgroup (π : FreeGroup α →* G) := Subgroup.closure (elements π)

theorem subgroup_le_ker (π : FreeGroup α →* G) : subgroup π ≤ π.ker := by
  apply (Subgroup.closure_le _).mpr
  rintro g ⟨w, rfl, hg⟩
  exact hg

theorem positive_mem (π : FreeGroup α →* G) (w : List α) (hw : π (positive w) = 1) :
    positive w ∈ subgroup π := Subgroup.subset_closure ⟨w, rfl, hw⟩

private theorem preserves_closure (π : FreeGroup α →* G) (f : FreeGroup α →* FreeGroup α)
    (hf : ∀ w, π (positive w) = 1 → f (positive w) ∈ subgroup π) :
    ∀ g ∈ subgroup π, f g ∈ subgroup π := by
  have h : subgroup π ≤ (subgroup π).comap f := by
    apply (Subgroup.closure_le _).mpr
    rintro _ ⟨w, rfl, hw⟩
    exact hf w hw
  exact h

/-- Both signs of every free generator preserve the subgroup of positive
kernel words by conjugation. -/
private theorem conjugation_generators (π : FreeGroup α →* G)
    (hpos : ∀ i : α, ∃ w : List α, π (positive w) = (π (FreeGroup.of i))⁻¹) (i : α) :
    (∀ g ∈ subgroup π, FreeGroup.of i * g * (FreeGroup.of i)⁻¹ ∈ subgroup π) ∧
    (∀ g ∈ subgroup π, (FreeGroup.of i)⁻¹ * g * FreeGroup.of i ∈ subgroup π) := by
  obtain ⟨v, hv⟩ := hpos i
  constructor
  · apply preserves_closure π (MulAut.conj (FreeGroup.of i)).toMonoidHom
    intro w hw
    have hfirst : positive ([i] ++ w ++ v) ∈ subgroup π := by
      apply positive_mem
      simp [map_mul, hv, hw]
    have hsecond : positive ([i] ++ v) ∈ subgroup π := by
      apply positive_mem
      simp [map_mul, hv]
    have h := Subgroup.mul_mem _ hfirst (Subgroup.inv_mem _ hsecond)
    convert h using 1
    simp [mul_assoc]
  · apply preserves_closure π (MulAut.conj (FreeGroup.of i)⁻¹).toMonoidHom
    intro w hw
    have hfirst : positive (v ++ [i]) ∈ subgroup π := by
      apply positive_mem
      simp [map_mul, hv]
    have hsecond : positive (v ++ w ++ [i]) ∈ subgroup π := by
      apply positive_mem
      simp [map_mul, hv, hw]
    have h := Subgroup.mul_mem _ (Subgroup.inv_mem _ hfirst) hsecond
    convert h using 1
    simp [mul_assoc]

/-- Under positive inverse spellings, positive kernel words generate a
normal subgroup even though only subgroup closure was taken. -/
theorem subgroup_normal (π : FreeGroup α →* G)
    (hpos : ∀ i : α, ∃ w : List α, π (positive w) = (π (FreeGroup.of i))⁻¹) :
    (subgroup π).Normal := by
  have hconj (c : FreeGroup α) : ∀ g ∈ subgroup π, c * g * c⁻¹ ∈ subgroup π := by
    induction c using FreeGroup.induction_on with
    | one => intro g hg; simpa using hg
    | of i => exact (conjugation_generators π hpos i).1
    | inv_of i ih =>
        simpa only [inv_inv] using (conjugation_generators π hpos i).2
    | mul c d hc hd =>
        intro g hg
        simpa only [mul_inv_rev, mul_assoc] using hc _ (hd g hg)
  exact ⟨fun g hg c => hconj c g hg⟩

/-- Every kernel element is a product of positive kernel words and their
inverses, provided inverse generators have positive spellings in the target. -/
theorem subgroup_eq_ker (π : FreeGroup α →* G)
    (hpos : ∀ i : α, ∃ w : List α, π (positive w) = (π (FreeGroup.of i))⁻¹) :
    subgroup π = π.ker := by
  let : (subgroup π).Normal := subgroup_normal π hpos
  let q := QuotientGroup.mk' (subgroup π)
  let f := QuotientGroup.lift (subgroup π) π (subgroup_le_ker π)
  have hpositive (g : FreeGroup α) : ∃ w : List α, q g = q (positive w) := by
    induction g using FreeGroup.induction_on with
    | one => exact ⟨[], rfl⟩
    | of i => exact ⟨[i], by simp⟩
    | inv_of i ih =>
        obtain ⟨w, hw⟩ := hpos i
        refine ⟨w, ?_⟩
        have hm : positive ([i] ++ w) ∈ subgroup π := by
          apply positive_mem
          simp [map_mul, hw]
        have hq : q (positive ([i] ++ w)) = 1 := (QuotientGroup.eq_one_iff _).mpr hm
        simp only [positive_append, positive_singleton, map_mul] at hq
        rw [map_inv]
        simpa only [inv_inv] using congrArg Inv.inv (eq_inv_of_mul_eq_one_left hq)
    | mul a b ha hb =>
        obtain ⟨u, hu⟩ := ha
        obtain ⟨v, hv⟩ := hb
        exact ⟨u ++ v, by rw [positive_append, map_mul, map_mul, hu, hv]⟩
  apply le_antisymm (subgroup_le_ker π)
  intro g hg
  obtain ⟨w, hw⟩ := hpositive g
  have hπ : π g = π (positive w) := congrArg f hw
  have hm : positive w ∈ subgroup π := positive_mem π w (hπ.symm.trans hg)
  apply (QuotientGroup.eq_one_iff _).mp
  change q g = 1
  rw [hw]
  exact (QuotientGroup.eq_one_iff _).mpr hm

end UniversalGroup.PositiveKernel
