module

public import Mathlib.Data.Fin.VecNotation

@[expose] public section

namespace UniversalGroup

/-- A finite-word Thue system, regarded as a symmetric rewriting system. -/
abbrev ThueSystem (α : Type*) :=
  Set (List α × List α)

/-- One application of a Thue rule in an arbitrary two-sided context. -/
def ThueStep {α : Type*}
    (T : ThueSystem α) (u v : List α) : Prop :=
  ∃ l r x y : List α,
    (x, y) ∈ T ∧
      ((u = l ++ x ++ r ∧ v = l ++ y ++ r) ∨
       (u = l ++ y ++ r ∧ v = l ++ x ++ r))

/-- Equality generated by finitely many Thue rewrites. -/
def ThueEq {α : Type*} (T : ThueSystem α) :=
  Relation.ReflTransGen (ThueStep T)

namespace Thue

theorem thueStep_symm {T : ThueSystem α} {X Y : List α}
    (h : ThueStep T X Y) : ThueStep T Y X := by
  rcases h with ⟨l, r, x, y, hxy, hwords⟩
  rcases hwords with ⟨hX, hY⟩ | ⟨hX, hY⟩
  · exact ⟨l, r, x, y, hxy, Or.inr ⟨hY, hX⟩⟩
  · exact ⟨l, r, x, y, hxy, Or.inl ⟨hY, hX⟩⟩

theorem thueEq_symm {T : ThueSystem α} {X Y : List α}
    (h : ThueEq T X Y) : ThueEq T Y X := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hstep ih =>
      exact (Relation.ReflTransGen.single (thueStep_symm hstep)).trans ih

theorem thueStep_context {T : ThueSystem α} (l r : List α)
    {X Y : List α} (h : ThueStep T X Y) :
    ThueStep T (l ++ X ++ r) (l ++ Y ++ r) := by
  rcases h with ⟨l', r', x, y, hxy, hwords⟩
  rcases hwords with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · exact ⟨l ++ l', r' ++ r, x, y, hxy,
      Or.inl ⟨by simp only [List.append_assoc], by simp only [List.append_assoc]⟩⟩
  · exact ⟨l ++ l', r' ++ r, x, y, hxy,
      Or.inr ⟨by simp only [List.append_assoc], by simp only [List.append_assoc]⟩⟩

theorem thueEq_context {T : ThueSystem α} (l r : List α)
    {X Y : List α} (h : ThueEq T X Y) :
    ThueEq T (l ++ X ++ r) (l ++ Y ++ r) :=
  h.lift (fun W ↦ l ++ W ++ r)
    (fun _ _ hstep ↦ thueStep_context l r hstep)

end Thue
end UniversalGroup

namespace UniversalGroup.Thue.Matiyasevich1993

/-- A finite family of word pairs determines a Thue system. -/
def finiteSystem {α : Type*} {r : ℕ} (F E : Fin r → List α) : ThueSystem α :=
  Set.range fun i => (F i, E i)

end UniversalGroup.Thue.Matiyasevich1993
