module

public import UniversalGroup.Host.EllStage

@[expose] public section

/-! Free subgroups generated by the input, `c`, and an HNN stable letter. -/

namespace UniversalGroup.InputFreeSubgroup

noncomputable section

abbrev Z := Multiplicative ℤ
abbrev Pair (G : Type*) [Group G] := Monoid.Coprod Z G

section CyclicSplit
universe u
variable {K : Type u} [Group K] (V : Subgroup K) (G : Type u) [Group G]
  (σ : Z →* K) (θ : K →* Z)
  (hsplit : θ.comp σ = MonoidHom.id Z) (hV : ∀ x : V, θ x = 1)

def pairHom : Pair G →* CentralizingAmalgam.Model V G :=
  Monoid.Coprod.lift ((CentralizingAmalgam.ofBase V G).comp σ)
    (CentralizingAmalgam.ofInput V G)

@[simp] theorem pairHom_inl (z : Z) :
    pairHom V G σ (Monoid.Coprod.inl z) = CentralizingAmalgam.ofBase V G (σ z) := by
  simp [pairHom]

@[simp] theorem pairHom_inr (g : G) :
    pairHom V G σ (Monoid.Coprod.inr g) = CentralizingAmalgam.ofInput V G g := by
  simp [pairHom]

def pairProjection : CentralizingAmalgam.Model V G →* Pair G :=
  CentralizingAmalgam.lift V G (Monoid.Coprod.inl.comp θ) Monoid.Coprod.inr (by
    intro x y
    simp only [MonoidHom.comp_apply, hV x, map_one]
    exact Commute.one_left _)

@[simp] theorem pairProjection_base (k : K) :
    pairProjection V G θ hV (CentralizingAmalgam.ofBase V G k) =
      Monoid.Coprod.inl (θ k) := by simp [pairProjection]

@[simp] theorem pairProjection_input (g : G) :
    pairProjection V G θ hV (CentralizingAmalgam.ofInput V G g) =
      Monoid.Coprod.inr g := by simp [pairProjection]

include hsplit in
theorem pairProjection_comp :
    (pairProjection V G θ hV).comp (pairHom V G σ) = MonoidHom.id _ := by
  apply Monoid.Coprod.hom_ext <;> apply MonoidHom.ext
  · intro z
    simpa using congrArg (Monoid.Coprod.inl : Z → Pair G) (DFunLike.congr_fun hsplit z)
  · intro g
    simp

include hsplit hV in
theorem pairHom_injective : Function.Injective (pairHom V G σ) :=
  Function.LeftInverse.injective (fun x => DFunLike.congr_fun
    (pairProjection_comp V G σ θ hsplit hV) x)

theorem toBase_pairHom : (CentralizingAmalgam.toBase V G).comp (pairHom V G σ) =
    σ.comp Monoid.Coprod.fst := by
  apply Monoid.Coprod.hom_ext <;> ext <;> simp

include hsplit hV in
theorem pairHom_inf_base : (pairHom V G σ).range ⊓ (CentralizingAmalgam.ofBase V G).range =
    ((CentralizingAmalgam.ofBase V G).comp σ).range := by
  apply le_antisymm
  · rintro x ⟨⟨w, rfl⟩, k, hk⟩
    have hw : w = Monoid.Coprod.inl (θ k) := by
      have h := congrArg (pairProjection V G θ hV) hk
      rw [pairProjection_base] at h
      have hp := DFunLike.congr_fun (pairProjection_comp V G σ θ hsplit hV) w
      change pairProjection V G θ hV (pairHom V G σ w) = w at hp
      rw [hp] at h
      exact h.symm
    exact ⟨θ k, by rw [hw]; simp⟩
  · rintro x ⟨z, rfl⟩
    exact ⟨⟨Monoid.Coprod.inl z, by simp⟩, ⟨σ z, rfl⟩⟩

variable {C : Type*} [Group C]
  (attach : C →* CentralizingAmalgam.Model V G) (τ : C →* K)
  (hτ : Function.Injective τ)
  (hρ : (CentralizingAmalgam.toBase V G).comp attach = τ)
  (hθ : θ.comp τ = 1)

include hsplit hτ hρ hθ in
theorem pairHom_disjoint : (pairHom V G σ).range ⊓ attach.range = ⊥ := by
  apply le_antisymm
  · rintro x ⟨⟨w, rfl⟩, a, ha⟩
    have hk : σ (Monoid.Coprod.fst w) = τ a := by
      have hh := congrArg (CentralizingAmalgam.toBase V G) ha
      change ((CentralizingAmalgam.toBase V G).comp attach) a =
        ((CentralizingAmalgam.toBase V G).comp (pairHom V G σ)) w at hh
      rw [hρ, toBase_pairHom] at hh
      exact hh.symm
    have hz : Monoid.Coprod.fst w = 1 := by
      have hh := congrArg θ hk
      change (θ.comp σ) (Monoid.Coprod.fst w) = (θ.comp τ) a at hh
      simpa [hsplit, hθ] using hh
    have ha1 : a = 1 := hτ (by rw [← hk, hz, map_one, map_one])
    rw [ha1, map_one] at ha
    exact ha.symm
  · exact bot_le

end CyclicSplit

section FreeStable
open HNNLemmas
variable {M W C : Type*} [Group M] [Group W] [Group C]
  (left right : C →* M) (hl : Function.Injective left) (hr : Function.Injective right)
  (σ : W →* M) (hσ : Function.Injective σ)
  (hleft : σ.range ⊓ left.range = ⊥) (hright : σ.range ⊓ right.range = ⊥)

include hleft hright in
private theorem preserves_range (a : left.range) :
    (a : M) ∈ σ.range ↔
      ((UniversalGroup.rangeEquiv left right hl hr a : right.range) : M) ∈ σ.range := by
  constructor
  · intro ha
    have he : (a : M) = 1 := by
      have hh : (a : M) ∈ σ.range ⊓ left.range := ⟨ha, a.property⟩
      simpa [hleft] using hh
    have he' : a = 1 := Subtype.ext he
    simp [he']
  · intro ha
    have he : ((UniversalGroup.rangeEquiv left right hl hr a : right.range) : M) = 1 := by
      have hh : ((UniversalGroup.rangeEquiv left right hl hr a : right.range) : M) ∈
          σ.range ⊓ right.range := ⟨ha, (UniversalGroup.rangeEquiv left right hl hr a).property⟩
      simpa [hright] using hh
    have he' : UniversalGroup.rangeEquiv left right hl hr a = 1 := Subtype.ext he
    have ha' : a = 1 := (UniversalGroup.rangeEquiv left right hl hr).injective (by simpa using he')
    simp [ha']

private abbrev Restricted :=
  HNNExtension σ.range (restrictedA (A := left.range) σ.range)
    (restrictedB (B := right.range) σ.range)
    (restrictedPhi (phi := UniversalGroup.rangeEquiv left right hl hr) σ.range
      (preserves_range left right hl hr σ hleft hright))

private def freeToRestricted : Monoid.Coprod W Z →* Restricted left right hl hr σ hleft hright :=
  Monoid.Coprod.lift (HNNExtension.of.comp σ.rangeRestrict)
    (zpowersHom _ HNNExtension.t⁻¹)

private def restrictedToFree : Restricted left right hl hr σ hleft hright →* Monoid.Coprod W Z :=
  HNNExtension.lift
    (Monoid.Coprod.inl.comp (MonoidHom.ofInjective hσ).symm.toMonoidHom)
    (Monoid.Coprod.inr (Multiplicative.ofAdd (1 : ℤ)))⁻¹ (by
      intro a
      have ha : a = 1 := by
        apply Subtype.ext
        apply Subtype.ext
        have hh : (((a : σ.range) : M)) ∈ σ.range ⊓ left.range :=
          ⟨(a : σ.range).property, a.property⟩
        simpa [hleft] using hh
      subst a
      simp)

include hσ in
private theorem freeToRestricted_injective :
    Function.Injective (freeToRestricted left right hl hr σ hleft hright) := by
  have h : (restrictedToFree left right hl hr σ hσ hleft hright).comp
      (freeToRestricted left right hl hr σ hleft hright) = MonoidHom.id _ := by
    apply Monoid.Coprod.hom_ext <;> apply MonoidHom.ext
    · intro w
      change Monoid.Coprod.inl ((MonoidHom.ofInjective hσ).symm (σ.rangeRestrict w)) =
        Monoid.Coprod.inl w
      congr 1
      exact (MonoidHom.ofInjective hσ).symm_apply_apply w
    · intro z
      simp only [MonoidHom.comp_apply, Monoid.Coprod.lift_apply_inr,
        freeToRestricted, zpowersHom_apply, map_zpow, map_inv, restrictedToFree,
        HNNExtension.lift_t, inv_inv, MonoidHom.id_apply]
      rw [← map_zpow]
      congr 1
      change Multiplicative.ofAdd ((Multiplicative.toAdd z) • (1 : ℤ)) = z
      simp
  exact Function.LeftInverse.injective (fun x => DFunLike.congr_fun h x)

/-- The original subgroup and the new stable letter generate their free product. -/
def freeStableHom : Monoid.Coprod W Z →* IdentifyingHNN left right hl hr :=
  Monoid.Coprod.lift ((IdentifyingHNN.of left right hl hr).comp σ)
    (zpowersHom _ (IdentifyingHNN.stable left right hl hr))

@[simp] theorem freeStableHom_inl (w : W) :
    freeStableHom left right hl hr σ (Monoid.Coprod.inl w) =
      IdentifyingHNN.of left right hl hr (σ w) := by simp [freeStableHom]

@[simp] theorem freeStableHom_inr (z : Z) :
    freeStableHom left right hl hr σ (Monoid.Coprod.inr z) =
      IdentifyingHNN.stable left right hl hr ^ Multiplicative.toAdd z := by
  simp [freeStableHom, zpowersHom_apply]

include hσ hleft hright in
theorem freeStableHom_injective :
    Function.Injective (freeStableHom left right hl hr σ) := by
  have h : (restrictedEmbedding (phi := UniversalGroup.rangeEquiv left right hl hr)
      σ.range (preserves_range left right hl hr σ hleft hright)).comp
      (freeToRestricted left right hl hr σ hleft hright) =
      freeStableHom left right hl hr σ := by
    apply Monoid.Coprod.hom_ext <;> ext <;>
      simp [freeToRestricted, freeStableHom, IdentifyingHNN.of, IdentifyingHNN.stable,
        zpowersHom_apply]
  rw [← h]
  exact (restrictedEmbedding_injective σ.range
    (preserves_range left right hl hr σ hleft hright)).comp
      (freeToRestricted_injective left right hl hr σ hσ hleft hright)

/-- The image has exactly the expected generators. -/
theorem freeStableHom_range :
    MonoidHom.range (G := Monoid.Coprod W Z) (freeStableHom left right hl hr σ) =
      generatedWithStable (phi := UniversalGroup.rangeEquiv left right hl hr) σ.range := by
  rw [freeStableHom, Monoid.Coprod.range_lift, MonoidHom.range_comp]
  change σ.range.map HNNExtension.of ⊔ Subgroup.zpowers HNNExtension.t⁻¹ = _
  rw [Subgroup.zpowers_inv, Subgroup.zpowers_eq_closure]
  rw [generatedWithStable, Subgroup.closure_union, Subgroup.closure_eq]

include hleft hright in
theorem freeStableHom_inf_base :
    MonoidHom.range (G := Monoid.Coprod W Z) (freeStableHom left right hl hr σ) ⊓
      (IdentifyingHNN.of left right hl hr).range =
      σ.range.map (IdentifyingHNN.of left right hl hr) := by
  rw [freeStableHom_range]
  exact generatedWithStable_inf_base σ.range
    (preserves_range left right hl hr σ hleft hright)

end FreeStable

section SimulatorExponent

/-- The exponent of `c`; every other displayed simulator letter has exponent zero. -/
def cValues : Fin 8 → Z := ![Multiplicative.ofAdd 1, 1, 1, 1, 1, 1, 1, 1]

theorem cValues_relators (D : CodeWords) (i : Fin 16) :
    Word.eval cValues ((simulatorK D).relator i) = 1 := by
  refine Fin.addCases (m := 13) (n := 3) (fun j => ?_) (fun j => ?_) i
  · simp only [simulatorK, Fin.append_left, Word.eval_mapGenerators]
    fin_cases j <;>
      simp [simulatorL, simulatorLRelators, simulatorLWords,
        SimulatorWords.positive, cValues, Function.comp_def]
  · simp only [simulatorK, Fin.append_right]
    fin_cases j <;>
      simp [simulatorLWords, SimulatorWords.positive, SimulatorWords.T,
        cValues, Function.comp_def]

def cExponent (D : CodeWords) : (simulatorK D).Group →* Z :=
  (simulatorK D).homOfRelators cValues (cValues_relators D)

@[simp] theorem cExponent_generator (D : CodeWords) (i : Fin 8) :
    cExponent D (generators (simulatorK D) i) = cValues i :=
  FP.homOfRelators_of _ _ _ _

def cPowers (D : CodeWords) : Z →* (simulatorK D).Group :=
  zpowersHom _ (generators (simulatorK D) 0)

theorem cExponent_comp_cPowers (D : CodeWords) :
    (cExponent D).comp (cPowers D) = MonoidHom.id Z := by
  ext
  simp [cPowers, zpowersHom_apply, cValues]

@[simp] theorem cExponent_old_word (D : CodeWords) (w : Word 7) :
    cExponent D (simulatorInclusion D ((simulatorL D).evalWord w)) =
      Word.eval (cValues ∘ Fin.castAdd 1) w := by
  rw [SimulatorCentralizer.inclusion_old_word, cExponent, FP.homOfRelators_evalWord,
    Word.eval_mapGenerators]

@[simp] theorem cExponent_gridValue (D : CodeWords) (i : Fin 4) :
    cExponent D (simulatorGridValues D i) = 1 := by
  refine Fin.cases ?_ (fun j => ?_) i
  · simp [simulatorGridValues, cValues]
  · simp only [simulatorGridValues, Fin.cons_succ, cExponent_old_word]
    fin_cases j <;> simp [SimulatorWords.x, SimulatorWords.positive,
      simulatorLWords, cValues, Function.comp_def]

theorem cExponent_grid (D : CodeWords) (x : simulatorGrid D) : cExponent D x = 1 := by
  have h : simulatorGrid D ≤ (cExponent D).ker := by
    rw [simulatorGrid, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact cExponent_gridValue D i
  exact h x.property

theorem cExponent_A (D : CodeWords) (x : simulatorA D) :
    cExponent D (simulatorInclusion D x) = 1 := by
  have h : simulatorA D ≤ ((cExponent D).comp (simulatorInclusion D)).ker := by
    rw [simulatorA, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    change cExponent D (simulatorInclusion D _) = 1
    rw [cExponent_old_word]
    fin_cases i <;> simp [simulatorLWords, SimulatorWords.positive,
      SimulatorWords.x, cValues, Function.comp_def]
  exact h x.property

theorem cExponent_B (D : CodeWords) (x : simulatorB D) :
    cExponent D (simulatorInclusion D x) = 1 := by
  have h : simulatorB D ≤ ((cExponent D).comp (simulatorInclusion D)).ker := by
    rw [simulatorB, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    change cExponent D (simulatorInclusion D _) = 1
    rw [cExponent_old_word]
    fin_cases i <;> simp [simulatorLWords, SimulatorWords.positive,
      SimulatorWords.T, cValues, Function.comp_def]
  exact h x.property

end SimulatorExponent

section Concrete
variable (G : PreparedInput) (D : ValievDatum G) (hintersections : ValievIntersections G D)

abbrev inputPairHom : Pair G.presentation.Group →* InputAmalgam G D.toCodeWords :=
  pairHom (simulatorGrid D.toCodeWords) G.presentation.Group (cPowers D.toCodeWords)

theorem inputPairHom_injective : Function.Injective (inputPairHom G D) :=
  pairHom_injective _ _ _ _ (cExponent_comp_cPowers D.toCodeWords) (cExponent_grid D.toCodeWords)

theorem cExponent_comp_toK :
    (cExponent D.toCodeWords).comp (EllStage.toK G D hintersections) = 1 := by
  apply ConjugatedAmalgam.hom_ext
  · intro x
    change cExponent D.toCodeWords (EllStage.toK G D hintersections
      (EllStage.inA G D hintersections x)) = 1
    rw [EllStage.toK_inA, cExponent_A]
  · intro x
    change cExponent D.toCodeWords (EllStage.toK G D hintersections
      (EllStage.inB G D hintersections x)) = 1
    rw [EllStage.toK_inB]
    simp [cExponent_B]

theorem inputPair_left_disjoint :
    (inputPairHom G D).range ⊓ (EllStage.left G D hintersections).range = ⊥ :=
  pairHom_disjoint _ _ _ _ (cExponent_comp_cPowers D.toCodeWords)
    (EllStage.left G D hintersections) (EllStage.toK G D hintersections)
    (EllStage.toK_injective G D hintersections) (EllStage.rho_comp_left G D hintersections)
    (cExponent_comp_toK G D hintersections)

theorem inputPair_right_disjoint :
    (inputPairHom G D).range ⊓ (EllStage.right G D hintersections).range = ⊥ :=
  pairHom_disjoint _ _ _ _ (cExponent_comp_cPowers D.toCodeWords)
    (EllStage.right G D hintersections) (EllStage.toK G D hintersections)
    (EllStage.toK_injective G D hintersections) (EllStage.rho_comp_right G D hintersections)
    (cExponent_comp_toK G D hintersections)

/-- `Z * G * Z`, with the outer cyclic factors represented by `c` and `ell`. -/
abbrev Domain := Monoid.Coprod (Pair G.presentation.Group) Z

def hom : Domain G →* EllStage.Model G D hintersections :=
  freeStableHom _ _ _ _ (inputPairHom G D)

theorem hom_injective : Function.Injective (hom G D hintersections) :=
  freeStableHom_injective _ _ _ _ _ (inputPairHom_injective G D)
    (inputPair_left_disjoint G D hintersections) (inputPair_right_disjoint G D hintersections)

@[simp] theorem hom_c (z : Z) :
    hom G D hintersections (Monoid.Coprod.inl (Monoid.Coprod.inl z)) =
      (EllStage.simulatorEmbedding G D hintersections).hom (cPowers D.toCodeWords z) := by
  simp [hom, EllStage.simulatorEmbedding, EllStage.ofM, EllStage.ofK]

@[simp] theorem hom_input (g : G.presentation.Group) :
    hom G D hintersections (Monoid.Coprod.inl (Monoid.Coprod.inr g)) =
      (EllStage.inputEmbedding G D hintersections).hom g := by
  simp [hom, EllStage.inputEmbedding, EllStage.ofM, inputAmalgamEmbedding]

@[simp] theorem hom_ell (z : Z) :
    hom G D hintersections (Monoid.Coprod.inr z) =
      EllStage.ell G D hintersections ^ Multiplicative.toAdd z := by
  simp [hom, EllStage.ell]

/-- The new free subgroup intersects the preceding amalgam exactly in `Z * G`. -/
theorem hom_inf_base :
    MonoidHom.range (G := Domain G) (hom G D hintersections) ⊓
      (EllStage.ofM G D hintersections).range =
      (inputPairHom G D).range.map (EllStage.ofM G D hintersections) :=
  freeStableHom_inf_base _ _ _ _ _
    (inputPair_left_disjoint G D hintersections) (inputPair_right_disjoint G D hintersections)

/-- The free subgroup meets the original simulator precisely in the powers of `c`. -/
theorem hom_inf_simulator :
    MonoidHom.range (G := Domain G) (hom G D hintersections) ⊓
      (EllStage.simulatorEmbedding G D hintersections).hom.range =
      ((EllStage.simulatorEmbedding G D hintersections).hom.comp (cPowers D.toCodeWords)).range := by
  apply le_antisymm
  · rintro x ⟨hx, k, hk⟩
    have hm : x ∈ (EllStage.ofM G D hintersections).range := ⟨EllStage.ofK G D k, hk⟩
    have hpair : x ∈ (inputPairHom G D).range.map (EllStage.ofM G D hintersections) := by
      rw [← hom_inf_base]
      exact ⟨hx, hm⟩
    rcases hpair with ⟨m, hm, hmx⟩
    have hmK : m ∈ (EllStage.ofK G D).range := by
      refine ⟨k, EllStage.ofM_injective G D hintersections ?_⟩
      exact hk.trans hmx.symm
    have hcyc : m ∈ ((EllStage.ofK G D).comp (cPowers D.toCodeWords)).range := by
      rw [show ((EllStage.ofK G D).comp (cPowers D.toCodeWords)).range =
          (inputPairHom G D).range ⊓ (EllStage.ofK G D).range from
        (pairHom_inf_base _ _ _ _ (cExponent_comp_cPowers D.toCodeWords)
          (cExponent_grid D.toCodeWords)).symm]
      exact ⟨hm, hmK⟩
    rcases hcyc with ⟨z, hz⟩
    exact ⟨z, by change EllStage.ofM G D hintersections
                   (((EllStage.ofK G D).comp (cPowers D.toCodeWords)) z) = x
                 rw [hz, hmx]⟩
  · rintro x ⟨z, rfl⟩
    exact ⟨⟨Monoid.Coprod.inl (Monoid.Coprod.inl z), hom_c G D hintersections z⟩,
      ⟨cPowers D.toCodeWords z, rfl⟩⟩

/-- The explicit image is generated by `c`, the input group, and `ell`. -/
theorem hom_range :
    MonoidHom.range (G := Domain G) (hom G D hintersections) =
      ((EllStage.simulatorEmbedding G D hintersections).hom.comp (cPowers D.toCodeWords)).range ⊔
        (EllStage.inputEmbedding G D hintersections).hom.range ⊔
        Subgroup.zpowers (EllStage.ell G D hintersections) := by
  rw [hom, freeStableHom, Monoid.Coprod.range_lift, MonoidHom.range_comp]
  rw [inputPairHom, pairHom, Monoid.Coprod.range_lift, Subgroup.map_sup]
  rw [MonoidHom.map_range, MonoidHom.map_range]
  rfl

/-- The concrete subgroup generated by these three factors. -/
abbrev subgroup : Subgroup (EllStage.Model G D hintersections) :=
  MonoidHom.range (G := Domain G) (hom G D hintersections)

end Concrete
end
end UniversalGroup.InputFreeSubgroup
