module

public import UniversalGroup.Simulator.Core.CStage
public import Mathlib.GroupTheory.SemidirectProduct

@[expose] public section

/-!
# A mod-five quotient of Borisov's two-HNN group

Both stable letters act on the free product `C₅ * C₅` by inverting each
free factor.  Since `4 = -1 (mod 5)`, the four power-conjugation relations of
`Gamma3` hold in the resulting semidirect product.  This quotient is useful
because every positive displayed rule contributes two nontrivial alternating
free-product syllables.
-/

namespace UniversalGroup
namespace BorisovModFiveQuotient

open BorisovHNNModel

noncomputable section

abbrev C5 := Multiplicative (ZMod 5)
abbrev ModFiveBase := Monoid.CoprodI (fun _ : Fin 2 ↦ C5)

def c5Generator : C5 := Multiplicative.ofAdd 1

def modD : ModFiveBase :=
  Monoid.CoprodI.of (i := (0 : Fin 2)) c5Generator

def modE : ModFiveBase :=
  Monoid.CoprodI.of (i := (1 : Fin 2)) c5Generator

def c5Inverse : C5 →* C5 where
  toFun x := x⁻¹
  map_one' := inv_one
  map_mul' x y := by simp [mul_comm]

def invertFactorsHom : ModFiveBase →* ModFiveBase :=
  Monoid.CoprodI.lift fun i ↦
    ((Monoid.CoprodI.of (M := fun _ : Fin 2 ↦ C5) (i := i)) :
      C5 →* ModFiveBase).comp c5Inverse

@[simp] theorem invertFactorsHom_of (i : Fin 2) (x : C5) :
    invertFactorsHom (Monoid.CoprodI.of (i := i) x) =
      Monoid.CoprodI.of (i := i) x⁻¹ := by
  simp [invertFactorsHom, c5Inverse]

theorem invertFactorsHom_involutive (x : ModFiveBase) :
    invertFactorsHom (invertFactorsHom x) = x := by
  induction x using Monoid.CoprodI.induction_on with
  | one => simp
  | of i x => simp
  | mul x y hx hy => simp [hx, hy]

def invertFactors : MulAut ModFiveBase where
  toFun := invertFactorsHom
  invFun := invertFactorsHom
  left_inv := invertFactorsHom_involutive
  right_inv := invertFactorsHom_involutive
  map_mul' := map_mul invertFactorsHom

@[simp] theorem invertFactors_modD : invertFactors modD = modD⁻¹ := by
  simp [invertFactors, modD]

@[simp] theorem invertFactors_modE : invertFactors modE = modE⁻¹ := by
  simp [invertFactors, modE]

/-- The infinite cyclic action generated by factorwise inversion.  Using an
infinite cyclic acting group avoids any quotient bookkeeping; the action
still has period two because `invertFactors` is involutive. -/
def inversionAction : Multiplicative ℤ →* MulAut ModFiveBase where
  toFun n := invertFactors ^ Multiplicative.toAdd n
  map_one' := by simp
  map_mul' x y := by simp [zpow_add]

abbrev QuotientGroup :=
  ModFiveBase ⋊[inversionAction] Multiplicative ℤ

def quotientBase : ModFiveBase →* QuotientGroup :=
  SemidirectProduct.inl

def quotientStable : QuotientGroup :=
  SemidirectProduct.inr (Multiplicative.ofAdd 1)

@[simp] theorem inversionAction_one :
    inversionAction (Multiplicative.ofAdd 1) = invertFactors := by
  simp [inversionAction]

@[simp] theorem quotientStable_mul_base (x : ModFiveBase) :
    quotientStable * quotientBase x =
      quotientBase (invertFactors x) * quotientStable := by
  apply SemidirectProduct.ext <;> simp [quotientStable, quotientBase]

def baseModFive : Base →* ModFiveBase :=
  FreeGroup.lift ![modD, modE]

@[simp] theorem baseModFive_d : baseModFive d = modD := by
  simp [baseModFive, d]

@[simp] theorem baseModFive_e : baseModFive e = modE := by
  simp [baseModFive, e]

theorem modD_pow_four : modD ^ 4 = modD⁻¹ := by
  rw [show modD = Monoid.CoprodI.of (i := (0 : Fin 2)) c5Generator by rfl,
    ← map_pow, ← map_inv]
  apply congrArg (Monoid.CoprodI.of (i := (0 : Fin 2)))
  apply Multiplicative.toAdd.injective
  change (4 : ZMod 5) = -1
  decide

theorem modE_pow_four : modE ^ 4 = modE⁻¹ := by
  rw [show modE = Monoid.CoprodI.of (i := (1 : Fin 2)) c5Generator by rfl,
    ← map_pow, ← map_inv]
  apply congrArg (Monoid.CoprodI.of (i := (1 : Fin 2)))
  apply Multiplicative.toAdd.injective
  change (4 : ZMod 5) = -1
  decide

theorem baseModFive_beta_eq_invert_alpha (x : Base) :
    baseModFive (beta x) = invertFactors (baseModFive (alpha x)) := by
  let lhs : Base →* ModFiveBase := baseModFive.comp beta
  let rhs : Base →* ModFiveBase :=
    invertFactors.toMonoidHom.comp (baseModFive.comp alpha)
  have h : lhs = rhs := by
    apply FreeGroup.ext_hom
    intro i
    fin_cases i
    · change modD ^ 4 = invertFactors modD
      rw [modD_pow_four, invertFactors_modD]
    · change modE = invertFactors (modE ^ 4)
      rw [map_pow, invertFactors_modE, inv_pow, modE_pow_four, inv_inv]
  exact DFunLike.congr_fun h x

def baseToQuotient : Base →* QuotientGroup :=
  quotientBase.comp baseModFive

theorem stable_power_relation (x : Base) :
    quotientStable * baseToQuotient (alpha x) =
      baseToQuotient (beta x) * quotientStable := by
  change quotientStable * quotientBase (baseModFive (alpha x)) =
    quotientBase (baseModFive (beta x)) * quotientStable
  rw [quotientStable_mul_base, baseModFive_beta_eq_invert_alpha]

theorem firstLiftCondition (a : A0) :
    quotientStable * baseToQuotient (a : Base) =
      baseToQuotient (phi0 a : Base) * quotientStable := by
  obtain ⟨x, rfl⟩ := inA0.surjective a
  simpa using stable_power_relation x

def stageOneToQuotient : Stage1 →* QuotientGroup :=
  HNNExtension.lift baseToQuotient quotientStable firstLiftCondition

@[simp] theorem stageOneToQuotient_of0 (x : Base) :
    stageOneToQuotient (of0 x) = baseToQuotient x := by
  simp [stageOneToQuotient, of0]

@[simp] theorem stageOneToQuotient_s1 :
    stageOneToQuotient s1 = quotientStable := by
  simp [stageOneToQuotient, s1]

theorem secondLiftCondition (a : A1) :
    quotientStable * stageOneToQuotient (a : Stage1) =
      stageOneToQuotient (phi1 a : Stage1) * quotientStable := by
  obtain ⟨a0, rfl⟩ := inA1.surjective a
  obtain ⟨x, rfl⟩ := inA0.surjective a0
  simpa [stageOneToQuotient, of0] using stable_power_relation x

def gamma3ToQuotient : Gamma3 →* QuotientGroup :=
  HNNExtension.lift stageOneToQuotient quotientStable secondLiftCondition

@[simp] theorem gamma3ToQuotient_of1 (x : Stage1) :
    gamma3ToQuotient (of1 x) = stageOneToQuotient x := by
  simp [gamma3ToQuotient, of1]

@[simp] theorem gamma3ToQuotient_d3 :
    gamma3ToQuotient d3 = quotientBase modD := by
  simp [d3, baseToQuotient, quotientBase]

@[simp] theorem gamma3ToQuotient_e3 :
    gamma3ToQuotient e3 = quotientBase modE := by
  simp [e3, baseToQuotient, quotientBase]

@[simp] theorem gamma3ToQuotient_s1 :
    gamma3ToQuotient s1_3 = quotientStable := by
  simp [s1_3]

@[simp] theorem gamma3ToQuotient_s2 :
    gamma3ToQuotient s2_3 = quotientStable := by
  simp [gamma3ToQuotient, s2_3]

end

end BorisovModFiveQuotient
end UniversalGroup

