module

public import UniversalGroup.Simulator.Core.RecognitionContexts

@[expose] public section

namespace UniversalGroup
namespace BorisovContextNormalForm

open HNNLemmas
open BorisovCStage
open BorisovHNNModel

noncomputable section

/-- The two trivial intersections with the free base, expressed in the
iterated-HNN model.  They imply the compatibility needed to restrict the
`c`-HNN extension to the cyclic subgroups generated by `d` and by `e`. -/
structure BaseIntersections (datum : UniversalGroup.SupportedRules) : Prop where
  u_inf_DE : U datum ⊓ DE3 = ⊥
  v_inf_DE : V datum ⊓ DE3 = ⊥

private theorem element_eq_one_of_mem_inf_bot
    {G : Type*} [Group G] {H K : Subgroup G}
    (hinter : H ⊓ K = ⊥) {x : G} (hxH : x ∈ H) (hxK : x ∈ K) :
    x = 1 := by
  have hx : x ∈ (⊥ : Subgroup G) := by
    rw [← hinter]
    exact ⟨hxH, hxK⟩
  simpa using hx

private theorem cEquiv_preserves_dCyclic
    (datum : UniversalGroup.SupportedRules) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) (a : U datum) :
    (a : Gamma3) ∈ dCyclic ↔
      (cEquiv datum hfree a : Gamma3) ∈ dCyclic := by
  constructor
  · intro ha
    have ha1 : (a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.u_inf_DE a.property
        (dCyclic_le_DE3 ha)
    have ha' : a = 1 := Subtype.ext ha1
    subst a
    simp
  · intro hpa
    have hpa1 : (cEquiv datum hfree a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.v_inf_DE
        (cEquiv datum hfree a).property (dCyclic_le_DE3 hpa)
    have hpa' : cEquiv datum hfree a = 1 := Subtype.ext hpa1
    have ha' : a = 1 := (cEquiv datum hfree).injective (by simpa using hpa')
    subst a
    simp

private theorem cEquiv_preserves_eCyclic
    (datum : UniversalGroup.SupportedRules) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) (a : U datum) :
    (a : Gamma3) ∈ eCyclic ↔
      (cEquiv datum hfree a : Gamma3) ∈ eCyclic := by
  constructor
  · intro ha
    have ha1 : (a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.u_inf_DE a.property
        (eCyclic_le_DE3 ha)
    have ha' : a = 1 := Subtype.ext ha1
    subst a
    simp
  · intro hpa
    have hpa1 : (cEquiv datum hfree a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.v_inf_DE
        (cEquiv datum hfree a).property (eCyclic_le_DE3 hpa)
    have hpa' : cEquiv datum hfree a = 1 := Subtype.ext hpa1
    have ha' : a = 1 := (cEquiv datum hfree).injective (by simpa using hpa')
    subst a
    simp

private theorem CD_le_generatedWithStable_d
    (datum : UniversalGroup.SupportedRules) (hfree : RankFiveFree datum) :
    CD datum hfree ≤
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) dCyclic := by
  rw [CD, Subgroup.closure_le]
  intro x hx
  rcases hx with hx | hx
  · have hc : x = c datum hfree := by simpa using hx
    subst x
    have ht : (HNNExtension.t : Gamma2 datum hfree) ∈
        generatedWithStable
          (A := U datum) (B := V datum) (phi := cEquiv datum hfree) dCyclic := by
      apply Subgroup.subset_closure
      exact Or.inr rfl
    simpa [c] using
      (generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) dCyclic).inv_mem ht
  · have hd : x = of3 datum hfree d3 := by simpa using hx
    subst x
    apply Subgroup.subset_closure
    apply Or.inl
    exact ⟨d3, Subgroup.subset_closure (by simp), rfl⟩

private theorem CE_le_generatedWithStable_e
    (datum : UniversalGroup.SupportedRules) (hfree : RankFiveFree datum) :
    CE datum hfree ≤
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) eCyclic := by
  rw [CE, Subgroup.closure_le]
  intro x hx
  rcases hx with hx | hx
  · have hc : x = c datum hfree := by simpa using hx
    subst x
    have ht : (HNNExtension.t : Gamma2 datum hfree) ∈
        generatedWithStable
          (A := U datum) (B := V datum) (phi := cEquiv datum hfree) eCyclic := by
      apply Subgroup.subset_closure
      exact Or.inr rfl
    simpa [c] using
      (generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) eCyclic).inv_mem ht
  · have he : x = of3 datum hfree e3 := by simpa using hx
    subst x
    apply Subgroup.subset_closure
    apply Or.inl
    exact ⟨e3, Subgroup.subset_closure (by simp), rfl⟩

/-- Every element of `<c,d>` has the irreducible left-context form used in
Borisov's Lemma 4. -/
theorem exists_leftContext_of_mem_CD
    (datum : UniversalGroup.SupportedRules) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) {x : Gamma2 datum hfree}
    (hx : x ∈ CD datum hfree) :
    ∃ L : LeftContext datum hfree, leftValue datum hfree L = x := by
  have hx' := CD_le_generatedWithStable_d datum hfree hx
  rcases exists_reducedWord_of_mem_generatedWithStable dCyclic
      (cEquiv_preserves_dCyclic datum hfree hinter) hx' with
    ⟨w, hw, hhead, hcoeff⟩
  exact ⟨⟨w, hhead, hcoeff⟩, hw⟩

/-- Every element of `<c,e>` has the irreducible right-context form used in
Borisov's Lemma 4. -/
theorem exists_rightContext_of_mem_CE
    (datum : UniversalGroup.SupportedRules) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) {x : Gamma2 datum hfree}
    (hx : x ∈ CE datum hfree) :
    ∃ R : RightContext datum hfree, rightValue datum hfree R = x := by
  have hx' := CE_le_generatedWithStable_e datum hfree hx
  rcases exists_reducedWord_of_mem_generatedWithStable eCyclic
      (cEquiv_preserves_eCyclic datum hfree hinter) hx' with
    ⟨w, hw, hhead, hcoeff⟩
  exact ⟨⟨w, hhead, hcoeff⟩, hw⟩

end

end BorisovContextNormalForm
end UniversalGroup
