module

public import UniversalGroup.Coding.Data
public import Mathlib.Algebra.Order.Group.Nat
public import Mathlib.Data.Nat.Cast.Order.Basic
public import Mathlib.Tactic.FinCases

@[expose] public section

/-!
# The literal Valiev simulator and the intersection interface

The seven-generator group `L` and its centralizer extension `K` have thirteen
and sixteen relators respectively. We retain the original letter `t`, so the
normalized centralizer letter is the word `q = t f⁻¹`.
The substantive intersection proof lives in `UniversalGroup.Simulator.Intersections`;
this module contains only the literal presentations, subgroups, and interfaces.
-/

namespace UniversalGroup

/-- The seven simulator letters, in any ambient word alphabet. -/
structure SimulatorWords (n : ℕ) where
  c : Word n
  d : Word n
  e : Word n
  s : Fin 2 → Word n
  f : Word n
  t : Word n

namespace SimulatorWords

def positive (w : SimulatorWords n) (v : PositiveWord) : Word n :=
  Word.substitutePositive (w.s 0) (w.s 1) v

def T (w : SimulatorWords n) (datum : CodeWords) : Word n :=
  Word.product [w.positive datum.P, w.t, Word.inverse w.f,
    Word.inverse (w.positive datum.P), w.f]

/-- The words `x₁,x₂,x₃` in the base group before `k` is adjoined. -/
def x (w : SimulatorWords n) (datum : CodeWords) : Fin 3 → Word n :=
  ![Word.product [Word.inverse w.f, w.s 0, w.f],
    Word.product [Word.inverse w.f, w.s 1, w.f],
    Word.product [w.positive datum.P, w.t]]

def bar (w : SimulatorWords n) (datum : CodeWords) (v : PositiveWord) : Word n :=
  w.positive (v.flatMap datum.code)

def delta (w : SimulatorWords n) (datum : CodeWords) (v : PositiveWord) : Word n :=
  Word.product [w.bar datum v, w.T datum, Word.inverse w.f,
    Word.inverse (w.bar datum v), w.f]

end SimulatorWords

/-- Generator order: `c,d,e,s₁,s₂,f,t`. -/
def simulatorLWords : SimulatorWords 7 where
  c := Word.generator 0
  d := Word.generator 1
  e := Word.generator 2
  s := ![Word.generator 3, Word.generator 4]
  f := Word.generator 5
  t := Word.generator 6

/-- The old thirteen relators, before the three commutations with `k`.
The three rule rows use indices `1,2,3`, as in the original simulator. -/
def simulatorLRelators (datum : CodeWords) (w : SimulatorWords n) : Fin 13 → Word n :=
  let rule (i : Fin 3) := Word.relation
    (Word.product [Word.inverse (Word.pow w.d (i.val + 1)), w.c,
      Word.pow w.d (i.val + 1), w.positive (datum.E i)])
    (Word.product [w.positive (datum.F i), Word.pow w.e (i.val + 1),
      w.c, Word.inverse (Word.pow w.e (i.val + 1))])
  ![Word.relation (Word.product [Word.pow w.d 4, w.s 0])
      (Word.product [w.s 0, w.d]),
    Word.relation (Word.product [Word.pow w.d 4, w.s 1])
      (Word.product [w.s 1, w.d]),
    Word.relation (Word.product [w.e, w.s 0])
      (Word.product [w.s 0, Word.pow w.e 4]),
    Word.relation (Word.product [w.e, w.s 1])
      (Word.product [w.s 1, Word.pow w.e 4]),
    Word.commutator w.c (w.s 0),
    Word.commutator w.c (w.s 1),
    rule 0, rule 1, rule 2,
    Word.commutator w.c w.f,
    Word.commutator w.d w.f,
    Word.commutator w.c w.t,
    Word.relation (Word.product [w.e, w.t])
      (Word.product [w.t, Word.inverse w.f, w.e, w.f])]

def simulatorL (datum : CodeWords) : FP 7 13 :=
  ⟨simulatorLRelators datum simulatorLWords⟩

/-- `K` has the old alphabet followed by `k`; its three new relators
centralize the exact subgroup generated by `T,c,d`. -/
def simulatorK (datum : CodeWords) : FP 8 16 where
  relator := Fin.append
    (fun i => Word.mapGenerators (Fin.castAdd 1) ((simulatorL datum).relator i))
    ![Word.commutator
        (Word.mapGenerators (Fin.castAdd 1) (simulatorLWords.T datum)) (Word.generator 7),
      Word.commutator (Word.generator 0) (Word.generator 7),
      Word.commutator (Word.generator 1) (Word.generator 7)]

/-- The natural inclusion on the old seven generators. -/
def simulatorInclusion (datum : CodeWords) :
    (simulatorL datum).Group →* (simulatorK datum).Group :=
  (simulatorL datum).homOfRelators
    (fun i => generators (simulatorK datum) (Fin.castAdd 1 i)) (fun i => by
      have h := (simulatorK datum).relator_eq_one (Fin.castAdd 3 i)
      rw [show (simulatorK datum).relator (Fin.castAdd 3 i) =
        Word.mapGenerators (Fin.castAdd 1) ((simulatorL datum).relator i) by
          simp only [simulatorK, Fin.append_left]] at h
      simpa only [FP.evalWord, Word.eval_mapGenerators, Function.comp_def, generators] using h)

/-- Killing `k` defines a retraction, without any recognition hypotheses. -/
def simulatorRetraction (datum : CodeWords) :
    (simulatorK datum).Group →* (simulatorL datum).Group :=
  (simulatorK datum).homOfRelators
    (Fin.append (generators (simulatorL datum)) ![1]) (by
      intro i
      refine Fin.addCases (m := 13) (n := 3) (fun j => ?_) (fun j => ?_) i
      · simp only [simulatorK, Fin.append_left, Word.eval_mapGenerators]
        have hvalues :
            (Fin.append (generators (simulatorL datum)) ![1]) ∘ Fin.castAdd 1 =
              generators (simulatorL datum) := by
          funext a
          simp
        rw [hvalues]
        exact (simulatorL datum).relator_eq_one j
      · simp only [simulatorK, Fin.append_right]
        fin_cases j <;> simp [Fin.append, Fin.addCases])

theorem simulatorRetraction_comp_inclusion (datum : CodeWords) :
    (simulatorRetraction datum).comp (simulatorInclusion datum) =
      MonoidHom.id (simulatorL datum).Group := by
  apply PresentedGroup.ext
  intro i
  simp [simulatorRetraction, simulatorInclusion, generators]

/-- The centralizer extension preserves its base group. -/
theorem simulatorInclusion_injective (datum : CodeWords) :
    Function.Injective (simulatorInclusion datum) := by
  have hleft : Function.LeftInverse (simulatorRetraction datum) (simulatorInclusion datum) := by
    intro a
    exact congrArg (fun f : (simulatorL datum).Group →* (simulatorL datum).Group => f a)
      (simulatorRetraction_comp_inclusion datum)
  exact hleft.injective

/-- Valiev's `D = ⟨c,d,T⟩`, a subgroup of `L`. -/
def simulatorD (datum : CodeWords) : Subgroup (simulatorL datum).Group :=
  Subgroup.closure (Set.range fun i : Fin 3 =>
    (simulatorL datum).evalWord
      (![simulatorLWords.c, simulatorLWords.d, simulatorLWords.T datum] i))

/-- Valiev's `A = ⟨ḡ₁,ḡ₂,x₁,x₂,x₃⟩`, a subgroup of `L`. -/
def simulatorA (datum : CodeWords) : Subgroup (simulatorL datum).Group :=
  Subgroup.closure (Set.range fun i : Fin 5 =>
    (simulatorL datum).evalWord
      (![simulatorLWords.positive (datum.code 0),
        simulatorLWords.positive (datum.code 1),
        simulatorLWords.x datum 0, simulatorLWords.x datum 1,
        simulatorLWords.x datum 2] i))

/-- Valiev's `B = ⟨ḡ₁,ḡ₂,f,T⟩`, a subgroup of `L`. -/
def simulatorB (datum : CodeWords) : Subgroup (simulatorL datum).Group :=
  Subgroup.closure (Set.range fun i : Fin 4 =>
    (simulatorL datum).evalWord
      (![simulatorLWords.positive (datum.code 0),
        simulatorLWords.positive (datum.code 1),
        simulatorLWords.f, simulatorLWords.T datum] i))

/-- `Δ(w) = w̄ T f⁻¹ w̄⁻¹ f`, evaluated in `L`. -/
def simulatorDelta (datum : CodeWords) (w : PositiveWord) : (simulatorL datum).Group :=
  (simulatorL datum).evalWord (simulatorLWords.delta datum w)

/-- The subgroup generated by the recognition elements for positive words
trivial in the prepared input monoid. -/
def recognitionSubgroup (G : PreparedInput) (datum : CodeWords) :
    Subgroup (simulatorL datum).Group :=
  Subgroup.closure {a | ∃ w : PositiveWord,
    PositiveEq G.monoidRules w [] ∧ simulatorDelta datum w = a}

/-- Exact subgroup equalities required by the changed-amalgam construction. -/
def ValievIntersections (G : PreparedInput) (D : ValievDatum G) : Prop :=
  simulatorD D.toCodeWords ⊓ simulatorA D.toCodeWords = recognitionSubgroup G D.toCodeWords ∧
  simulatorD D.toCodeWords ⊓ simulatorB D.toCodeWords = recognitionSubgroup G D.toCodeWords

/-- A recognized positive word supplies an element of both exact intersections. -/
theorem simulatorDelta_mem_intersections (G : PreparedInput) (D : ValievDatum G)
    (hintersections : ValievIntersections G D) (w : PositiveWord)
    (hw : PositiveEq G.monoidRules w []) :
    simulatorDelta D.toCodeWords w ∈ simulatorD D.toCodeWords ⊓ simulatorA D.toCodeWords ∧
    simulatorDelta D.toCodeWords w ∈ simulatorD D.toCodeWords ⊓ simulatorB D.toCodeWords := by
  have hmem : simulatorDelta D.toCodeWords w ∈ recognitionSubgroup G D.toCodeWords :=
    Subgroup.subset_closure ⟨w, hw, rfl⟩
  rw [hintersections.1, hintersections.2]
  exact ⟨hmem, hmem⟩

end UniversalGroup
